# Generated by Django 2.0.7 on 2020-01-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M21DOCNEW1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=50, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=50, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=50, null=True)),
                ('desgn', models.CharField(blank=True, db_column='DESGN', max_length=50, null=True)),
                ('lastWeekPerHour', models.CharField(blank=True, db_column='LATWEEKPERHOUR', max_length=50, null=True)),
                ('lastWeekPerAmount', models.CharField(blank=True, db_column='LASTWEEKPERAMOUNT', max_length=50, null=True)),
                ('baseRatePerHour', models.CharField(blank=True, db_column='BASERATEPERHOUR', max_length=50, null=True)),
                ('baseRatePerHourAmount', models.CharField(blank=True, db_column='BASRRATEPERAMOUNT', max_length=50, null=True)),
                ('cutTimeDay', models.CharField(blank=True, db_column='CUTTIMEDAY', max_length=50, null=True)),
                ('cutTimeHours', models.CharField(blank=True, db_column='CUTTIMEHOUR', max_length=50, null=True)),
                ('additionalWagesDay', models.CharField(blank=True, db_column='ADDITIONALWAGESDAY', max_length=50, null=True)),
                ('additionalWagesHours', models.CharField(blank=True, db_column='ADDITIONALWAGESHOURS', max_length=50, null=True)),
                ('factoryHalfDay', models.CharField(blank=True, db_column='FACTORYHALFDAY', max_length=50, null=True)),
                ('factoryHalfHours', models.CharField(blank=True, db_column='FACTORYHALFHOURS', max_length=50, null=True)),
                ('generalOTDay', models.CharField(blank=True, db_column='GENERALOTDAY', max_length=50, null=True)),
                ('generalOTHours', models.CharField(blank=True, db_column='GENERALOTHOUR', max_length=50, null=True)),
                ('nightAllowanceDay', models.CharField(blank=True, db_column='NIGHTALLOWANCEDAY', max_length=50, null=True)),
                ('nightAllowanceHours', models.CharField(blank=True, db_column='NIGHTALLOWANCEHOUR', max_length=50, null=True)),
                ('halfHolidayDay', models.CharField(blank=True, db_column='HALFHOLIDAYDAY', max_length=50, null=True)),
                ('halfHolidayHours', models.CharField(blank=True, db_column='HALFHOLIDAYHOUR', max_length=50, null=True)),
                ('payOffLeaveDay', models.CharField(blank=True, db_column='PAYOFFLEAVEDAY', max_length=50, null=True)),
                ('payOffLeaveHours', models.CharField(blank=True, db_column='PAYOFFLEAVEHOUR', max_length=50, null=True)),
                ('unusedHolidaysDay', models.CharField(blank=True, db_column='UNUSEDHOLIDAYDAY', max_length=50, null=True)),
                ('unusedHolidaysHours', models.CharField(blank=True, db_column='UNUSEDHOLIDAYHOUR', max_length=50, null=True)),
                ('supplementaryHolidaysDay', models.CharField(blank=True, db_column='SUPPLEMENTARYHOLIDAYDAY', max_length=50, null=True)),
                ('supplementaryHolidaysHours', models.CharField(blank=True, db_column='SUPPLEMENTARYHOLIDAYHOUR', max_length=50, null=True)),
                ('date', models.CharField(blank=True, db_column='DATE', max_length=50, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN_TIME', max_length=50, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT_TIME', max_length=50, null=True)),
                ('outdate', models.CharField(blank=True, db_column='OUTDATE', max_length=50, null=True)),
                ('in2', models.CharField(blank=True, db_column='IN_TIME_OVER_TIME', max_length=50, null=True)),
                ('out2', models.CharField(blank=True, db_column='OUT_TIME_OVER_TIME', max_length=50, null=True)),
                ('total_time', models.CharField(blank=True, db_column='TOTAL_TIME', max_length=50, null=True)),
            ],
            options={
                'db_table': 'M21DOCNEW1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MG47_table1',
            fields=[
                ('to_sse', models.CharField(blank=True, db_column='ToSSE', default=0, max_length=50, null=True)),
                ('num', models.CharField(db_column='No.', max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='Date', max_length=50, null=True)),
                ('allocable_to', models.CharField(blank=True, db_column='allocable_to', default=0, max_length=50, null=True)),
                ('issued_on', models.CharField(blank=True, db_column='Issued_on', max_length=20, null=True)),
                ('empno', models.CharField(blank=True, db_column='EmployeeID', default=0, max_length=50, null=True)),
                ('from_sse', models.CharField(blank=True, db_column='FromSSE', default=0, max_length=50, null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGINID', max_length=10, null=True)),
                ('current_date', models.DateTimeField(blank=True, db_column='CURRENTDATE', null=True)),
            ],
            options={
                'db_table': 'MG47_table1',
            },
        ),
        migrations.CreateModel(
            name='MG47_table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(db_column='description', max_length=50, null=True)),
                ('demand', models.CharField(db_column='QTY_demand', max_length=50, null=True)),
                ('issued', models.CharField(db_column='QTY_issued', max_length=50, null=True)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlw.MG47_table1')),
            ],
            options={
                'db_table': 'MG47_table2',
            },
        ),
    ]
