# Generated by Django 2.0.7 on 2019-09-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oprn',
            options={'managed': False},
        ),
    ]
