# Generated by Django 2.0.7 on 2020-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempm14M4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(blank=True, db_column='DOC_CODE', max_length=2, null=True)),
                ('doc_no', models.DecimalField(blank=True, db_column='DOC_NO', decimal_places=0, max_digits=10, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('pm_no', models.CharField(blank=True, db_column='PM_NO', max_length=5, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=8, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=8, null=True)),
                ('l_fr', models.CharField(blank=True, db_column='L_FR', max_length=4, null=True)),
                ('l_to', models.CharField(blank=True, db_column='L_TO', max_length=4, null=True)),
                ('bo_no', models.CharField(blank=True, db_column='BO_NO', max_length=7, null=True)),
                ('assly_no', models.CharField(blank=True, db_column='ASSLY_NO', max_length=8, null=True)),
                ('seq', models.DecimalField(blank=True, db_column='SEQ', decimal_places=3, max_digits=8, null=True)),
                ('due_wk', models.CharField(blank=True, db_column='DUE_WK', max_length=4, null=True)),
                ('brn_no', models.DecimalField(blank=True, db_column='BRN_NO', decimal_places=3, max_digits=8, null=True)),
                ('doc_ind', models.CharField(blank=True, db_column='DOC_IND', max_length=1, null=True)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=2, null=True)),
                ('epc', models.CharField(blank=True, db_column='EPC', max_length=2, null=True)),
            ],
            options={
                'db_table': 'TEMPM14_M4',
                'managed': False,
            },
        ),
    ]
