# Generated by Django 2.0.7 on 2020-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearMissIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10, null=True)),
                ('login_id', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('incident_date', models.CharField(max_length=20, null=True)),
                ('incident_time', models.CharField(max_length=20, null=True)),
                ('incident_location', models.CharField(max_length=30, null=True)),
                ('unit_section', models.CharField(max_length=15, null=True)),
                ('sse_id', models.CharField(max_length=20, null=True)),
                ('sse_name', models.CharField(max_length=50, null=True)),
                ('sse_designation', models.CharField(max_length=50, null=True)),
                ('fire_explosion', models.CharField(max_length=200, null=True)),
                ('employee_involve_id', models.CharField(max_length=20, null=True)),
                ('employee_involve_name', models.CharField(max_length=50, null=True)),
                ('employee_involve_designation', models.CharField(max_length=50, null=True)),
                ('otherinvolve', models.CharField(max_length=200, null=True)),
                ('incident_description', models.CharField(max_length=200, null=True)),
                ('details_of_damages_to_infrastructure', models.CharField(max_length=500, null=True)),
                ('site_sketch', models.FileField(blank=True, null=True, upload_to='investigationdoc/')),
                ('section_bay', models.CharField(max_length=15, null=True)),
                ('plant_machine_tools', models.CharField(max_length=20, null=True)),
                ('condition_of_work_environment', models.CharField(max_length=200, null=True)),
                ('others', models.CharField(max_length=300, null=True)),
                ('details_of_analysis_of_incident', models.CharField(max_length=500, null=True)),
                ('responsibility', models.CharField(max_length=500, null=True)),
                ('prevention_and_corrective_action', models.CharField(max_length=500, null=True)),
                ('comments_of_au_incharge', models.CharField(max_length=200, null=True)),
                ('au_incharge_id', models.CharField(max_length=20, null=True)),
                ('au_incharge_name', models.CharField(max_length=50, null=True)),
                ('au_incharge_designation', models.CharField(max_length=50, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
