# Generated by Django 2.0.7 on 2020-07-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m23doc',
            name='sno',
        ),
        migrations.RemoveField(
            model_name='m23doc',
            name='todate',
        ),
    ]
