# Generated by Django 2.0.7 on 2019-12-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M4HW',
        ),
    ]
