# Generated by Django 2.0.7 on 2019-11-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ms_tools_calibration',
        ),
        migrations.DeleteModel(
            name='ms_tools_Frequency',
        ),
        migrations.DeleteModel(
            name='ms_tools_group',
        ),
        migrations.DeleteModel(
            name='ms_tools_issue',
        ),
        migrations.DeleteModel(
            name='ms_tools_master',
        ),
        migrations.DeleteModel(
            name='ms_tools_receipt',
        ),
        migrations.DeleteModel(
            name='ms_tools_shopchange',
        ),
        migrations.DeleteModel(
            name='ms_tools_shops',
        ),
    ]
