# Generated by Django 2.0.7 on 2019-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axlewheelmachining',
            name='axlefitting_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='dispatch_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='wheelfitting_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m5shemp',
            name='date',
            field=models.CharField(blank=True, db_column='DATE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='m5shemp',
            name='flag',
            field=models.CharField(blank=True, db_column='FLAG', default='A', max_length=1, null=True),
        ),
    ]
