# Generated by Django 2.0.7 on 2019-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mg33new',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
