# Generated by Django 2.0.7 on 2019-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelw', models.CharField(blank=True, db_column='DATELW', default=0, max_length=20, null=True)),
                ('datecc', models.CharField(blank=True, db_column='DATECC', default=0, max_length=20, null=True)),
                ('daterw', models.CharField(blank=True, db_column='DATERW', default=0, max_length=20, null=True)),
                ('briefdd', models.CharField(blank=True, db_column='BRIEFDD', max_length=50, null=True)),
                ('no_hrs', models.CharField(blank=True, db_column='NO_HRS', max_length=4, null=True)),
                ('wo_no', models.CharField(blank=True, db_column='WORK_ORDER_JOB_LEFT', max_length=7, null=True)),
                ('wo_no1', models.CharField(blank=True, db_column='WORK_ORDER_TIME_ON_DUTY', max_length=7, null=True)),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=10, null=True)),
                ('month', models.CharField(blank=True, db_column='MONTH', max_length=10, null=True)),
            ],
            options={
                'db_table': 'M22',
            },
        ),
    ]
