# Generated by Django 2.0.7 on 2020-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_tempm14expl'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_year', models.CharField(blank=True, db_column='holiday_year', max_length=4, null=True)),
                ('holiday_name', models.CharField(blank=True, db_column='holiday_name', max_length=30, null=True)),
                ('holiday_date', models.CharField(blank=True, db_column='holiday_date', max_length=10, null=True)),
                ('holiday_type', models.CharField(blank=True, db_column='holiday_type', max_length=2, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=100, null=True)),
            ],
            options={
                'db_table': 'holidaylist',
            },
        ),
        migrations.AddField(
            model_name='m20new',
            name='shift',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
