# Generated by Django 2.0.7 on 2019-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_m22'),
    ]

    operations = [
        migrations.CreateModel(
            name='M18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopIncharge', models.CharField(blank=True, db_column='SHOPINCHARGE', default=0, max_length=20, null=True)),
                ('shop_sec', models.CharField(blank=True, db_column='SHOPSEC', default=0, max_length=20, null=True)),
                ('wo_no', models.CharField(blank=True, db_column='WONO', default=0, max_length=20, null=True)),
                ('part_nop', models.CharField(blank=True, db_column='PARTNOP', max_length=50, null=True)),
                ('extraTimePartNo', models.CharField(blank=True, db_column='EXTRATIMEPARTNO', max_length=4, null=True)),
                ('reasonSpecialAllowance', models.CharField(blank=True, db_column='REASON_SPCL_ALLOW', max_length=7, null=True)),
                ('forSpecialAllowance', models.CharField(blank=True, db_column='FOR_SPCL_ALLOW', max_length=7, null=True)),
                ('totalExtraTime', models.CharField(blank=True, db_column='TOTAL_EXTRA_TIME', max_length=4, null=True)),
                ('opno', models.CharField(blank=True, db_column='OPNO', max_length=10, null=True)),
                ('opdesc', models.CharField(blank=True, db_column='OPDESC', max_length=10, null=True)),
                ('discription', models.CharField(blank=True, db_column='DISCRIPTION', max_length=7, null=True)),
                ('quantity', models.CharField(blank=True, db_column='QUANTITY', max_length=4, null=True)),
                ('setExtraTime', models.CharField(blank=True, db_column='SET_EXTRA_TIME', max_length=7, null=True)),
                ('setno', models.CharField(blank=True, db_column='SETNO', max_length=4, null=True)),
            ],
            options={
                'db_table': 'M18',
            },
        ),
    ]
