# Generated by Django 2.0.7 on 2020-07-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_auto_20200717_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='m23doc',
            name='sno',
            field=models.CharField(blank=True, db_column='SNo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='m23doc',
            name='todate',
            field=models.CharField(blank=True, db_column='TO_DATE', max_length=20, null=True),
        ),
    ]
