# Generated by Django 2.0.7 on 2020-01-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_m21docnew1_mg47_table1_mg47_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_tools',
            fields=[
                ('letter_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shop_no', models.CharField(max_length=4)),
                ('shop_desc', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=20)),
                ('new_requirement', models.CharField(max_length=10)),
                ('modification', models.CharField(max_length=10)),
                ('additional', models.CharField(max_length=10)),
                ('existing_drawing', models.CharField(default='NONE', max_length=40)),
                ('component_drawing', models.CharField(max_length=40)),
                ('machine_no', models.CharField(max_length=20)),
                ('machine_description', models.CharField(max_length=50)),
                ('wsm_id', models.CharField(max_length=20)),
                ('sse_id', models.CharField(max_length=20)),
                ('wsm_name', models.CharField(max_length=50)),
                ('wsm_mobile', models.CharField(default='NONE', max_length=10)),
                ('sse_name', models.CharField(max_length=50)),
                ('sse_mobile', models.CharField(default='NONE', max_length=10)),
                ('name_supervisor', models.CharField(max_length=50)),
                ('desig_supervisor', models.CharField(max_length=50)),
                ('mobile_supervisor', models.CharField(default='NONE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mdescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('lno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tooling1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_designer', models.CharField(max_length=50)),
                ('date_designer', models.CharField(max_length=20)),
                ('name_guide', models.CharField(max_length=50)),
                ('date_guide', models.CharField(max_length=20)),
                ('date_completion', models.CharField(max_length=20)),
                ('date_loading', models.CharField(max_length=20)),
                ('sno_loading', models.CharField(max_length=20)),
                ('commment1', models.CharField(default='NONE', max_length=200)),
                ('commment2', models.CharField(default='NONE', max_length=200)),
                ('lno', models.CharField(max_length=20)),
            ],
        ),
    ]
