# Generated by Django 2.0.7 on 2019-11-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_auto_20191119_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mg33new',
            name='designation',
        ),
    ]
