# Generated by Django 2.0.7 on 2020-05-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_annual_production_axlemachining_axlewheelpressing_barrelfirst_bogieassembly_correctiveaction_cstr_bu'),
    ]

    operations = [

    ]
