# Generated by Django 2.0.7 on 2019-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_auto_20191118_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinionpressing',
            name='bo_qty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='dispatch_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='pt_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
