# Generated by Django 2.0.7 on 2019-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_auto_20190925_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machiningairbox',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
