# Generated by Django 2.0.7 on 2020-05-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_mg47_table1_mg47_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG47_table1',
            fields=[
                ('num', models.CharField(db_column='Sr.No.', max_length=50, primary_key=True, serialize=False)),
                ('shop', models.CharField(db_column='Shop', max_length=50, null=True)),
                ('to_sse', models.CharField(db_column='ToSSE', max_length=50, null=True)),
                ('date', models.CharField(db_column='Date', max_length=50, null=True)),
                ('allocable_to', models.CharField(db_column='allocable_to', max_length=50, null=True)),
                ('issued_on', models.CharField(db_column='Issued_on', max_length=20, null=True)),
                ('empno', models.CharField(db_column='EmployeeID', max_length=50, null=True)),
                ('from_sse', models.CharField(db_column='FromSSE', max_length=50, null=True)),
                ('empname', models.CharField(db_column='Empname', max_length=100, null=True)),
            ],
            options={
                'db_table': 'MG47_table1',
            },
        ),
        migrations.CreateModel(
            name='MG47_table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(db_column='description', max_length=50, null=True)),
                ('demand', models.CharField(db_column='QTY_demand', max_length=50, null=True)),
                ('issued', models.CharField(db_column='QTY_issued', max_length=50, null=True)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlw.MG47_table1')),
            ],
            options={
                'db_table': 'MG47_table2',
            },
        ),
    ]
