# Generated by Django 2.0.7 on 2020-03-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_roster1'),
    ]

    operations = [
        migrations.AddField(
            model_name='m22',
            name='hd1',
            field=models.CharField(blank=True, db_column='HD1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd10',
            field=models.CharField(blank=True, db_column='HD10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd11',
            field=models.CharField(blank=True, db_column='HD11', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd12',
            field=models.CharField(blank=True, db_column='HD12', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd13',
            field=models.CharField(blank=True, db_column='HD13', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd14',
            field=models.CharField(blank=True, db_column='HD14', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd15',
            field=models.CharField(blank=True, db_column='HD15', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd16',
            field=models.CharField(blank=True, db_column='HD16', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd17',
            field=models.CharField(blank=True, db_column='HD17', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd18',
            field=models.CharField(blank=True, db_column='HD18', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd19',
            field=models.CharField(blank=True, db_column='HD19', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd2',
            field=models.CharField(blank=True, db_column='HD2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd20',
            field=models.CharField(blank=True, db_column='HD20', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd21',
            field=models.CharField(blank=True, db_column='HD21', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd22',
            field=models.CharField(blank=True, db_column='HD22', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd23',
            field=models.CharField(blank=True, db_column='HD23', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd24',
            field=models.CharField(blank=True, db_column='HD24', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd25',
            field=models.CharField(blank=True, db_column='HD25', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd26',
            field=models.CharField(blank=True, db_column='HD26', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd27',
            field=models.CharField(blank=True, db_column='HD27', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd28',
            field=models.CharField(blank=True, db_column='HD28', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd29',
            field=models.CharField(blank=True, db_column='HD29', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd3',
            field=models.CharField(blank=True, db_column='HD3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd30',
            field=models.CharField(blank=True, db_column='HD30', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd31',
            field=models.CharField(blank=True, db_column='HD31', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd4',
            field=models.CharField(blank=True, db_column='HD4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd5',
            field=models.CharField(blank=True, db_column='HD5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd6',
            field=models.CharField(blank=True, db_column='HD6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd7',
            field=models.CharField(blank=True, db_column='HD7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd8',
            field=models.CharField(blank=True, db_column='HD8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='hd9',
            field=models.CharField(blank=True, db_column='HD9', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='m22',
            name='wo_no',
            field=models.CharField(blank=True, db_column='WORK_ORDER_JOB_LEFT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m22',
            name='wo_no1',
            field=models.CharField(blank=True, db_column='WORK_ORDER_TIME_ON_DUTY', max_length=10, null=True),
        ),
    ]
