# Generated by Django 2.0.7 on 2020-07-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_auto_20200717_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mg47_table2',
            name='num',
        ),
        migrations.DeleteModel(
            name='MG47_table1',
        ),
        migrations.DeleteModel(
            name='MG47_table2',
        ),
    ]
