# Generated by Django 2.0.7 on 2019-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_auto_20191004_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='m1card',
            fields=[
                ('idn', models.AutoField(primary_key=True, serialize=False)),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('des', models.CharField(blank=True, db_column='DES', max_length=30, null=True)),
                ('drgno', models.CharField(blank=True, db_column='DRGNO', max_length=18, null=True)),
                ('drg_alt', models.CharField(blank=True, db_column='DRG_ALT', max_length=5, null=True)),
                ('spec', models.CharField(blank=True, db_column='SPEC', max_length=20, null=True)),
                ('size_m', models.CharField(blank=True, db_column='SIZE_M', max_length=30, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='WEIGHT', decimal_places=3, max_digits=9, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('m14splt_cd', models.CharField(blank=True, db_column='M14SPLT_CD', max_length=1, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('allow_perc', models.DecimalField(blank=True, db_column='ALLOW_PERC', decimal_places=0, max_digits=2, null=True)),
                ('rate', models.DecimalField(blank=True, db_column='RATE', decimal_places=2, max_digits=10, null=True)),
                ('rate_date', models.DateField(blank=True, db_column='RATE_DATE', null=True)),
                ('alt_link', models.DecimalField(blank=True, db_column='ALT_LINK', decimal_places=0, max_digits=4, null=True)),
                ('part_grp', models.CharField(blank=True, db_column='PART_GRP', max_length=8, null=True)),
                ('updt_dt', models.DateField(blank=True, db_column='UPDT_DT', null=True)),
                ('del_fl', models.CharField(blank=True, db_column='DEL_FL', max_length=1, null=True)),
                ('flag_hw', models.CharField(blank=True, db_column='FLAG_HW', max_length=2, null=True)),
                ('m14_flag', models.CharField(blank=True, db_column='M14_FLAG', max_length=1, null=True)),
                ('mark', models.CharField(blank=True, db_column='MARK', max_length=1, null=True)),
                ('u_f', models.CharField(blank=True, db_column='U_F', max_length=1, null=True)),
            ],
        ),
    ]
