# Generated by Django 2.0.7 on 2019-12-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_m4hw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M4HW',
        ),
    ]
