# Generated by Django 2.0.7 on 2020-03-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_auto_20200327_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dpo',
        ),
    ]
