# Generated by Django 2.0.7 on 2020-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_tempm14m4new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempm14m4new',
            name='brn_no',
            field=models.DecimalField(blank=True, db_column='BRN_NO', decimal_places=0, max_digits=8, null=True),
        ),
    ]
