# Generated by Django 2.0.7 on 2019-11-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_remove_mg33new_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mg33new',
            name='acc_date',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='foreman',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='oral_score',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='place',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='place_of_exam',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='prac_score',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='sec_sup',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='shop_sec',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='ticketno',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='trade_test_admin',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='trade_test_officer',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='updt_date',
        ),
        migrations.AddField(
            model_name='mg33new',
            name='exam_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='exam_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
