# Generated by Django 2.0.7 on 2019-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_auto_20191118_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('shop_sec', models.CharField(blank=True, max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_arr', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_dept', models.CharField(blank=True, max_length=10, null=True)),
                ('time_arr', models.CharField(blank=True, max_length=10, null=True)),
                ('time_dept', models.CharField(blank=True, max_length=10, null=True)),
                ('hosp_arr', models.CharField(blank=True, max_length=10, null=True)),
                ('hosp_dept', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('resumed_time', models.CharField(blank=True, max_length=10, null=True)),
                ('resumed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('dept', models.CharField(blank=True, max_length=10, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('med_officer', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date_app', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
