# Generated by Django 2.0.7 on 2019-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_auto_20191017_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpoloco',
            name='endcumno',
        ),
        migrations.AddField(
            model_name='dpoloco',
            name='batchordno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dpoloco',
            name='cumino',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dpoloco',
            name='qtybatch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dpo',
            name='procedureno',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dpoloco',
            name='procedureno',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
