# Generated by Django 2.0.7 on 2019-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_m18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m18',
            name='discription',
            field=models.CharField(blank=True, db_column='DISCRIPTION', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='extraTimePartNo',
            field=models.CharField(blank=True, db_column='EXTRATIMEPARTNO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='forSpecialAllowance',
            field=models.CharField(blank=True, db_column='FOR_SPCL_ALLOW', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='opdesc',
            field=models.CharField(blank=True, db_column='OPDESC', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='opno',
            field=models.CharField(blank=True, db_column='OPNO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='quantity',
            field=models.CharField(blank=True, db_column='QUANTITY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='reasonSpecialAllowance',
            field=models.CharField(blank=True, db_column='REASON_SPCL_ALLOW', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='setExtraTime',
            field=models.CharField(blank=True, db_column='SET_EXTRA_TIME', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='setno',
            field=models.CharField(blank=True, db_column='SETNO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='shopIncharge',
            field=models.CharField(blank=True, db_column='SHOPINCHARGE', default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='shop_sec',
            field=models.CharField(blank=True, db_column='SHOPSEC', default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='totalExtraTime',
            field=models.CharField(blank=True, db_column='TOTAL_EXTRA_TIME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m18',
            name='wo_no',
            field=models.CharField(blank=True, db_column='WONO', default=0, max_length=50, null=True),
        ),
    ]
