# Generated by Django 2.0.7 on 2019-11-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_ms_tools_calibration_ms_tools_frequency_ms_tools_group_ms_tools_issue_ms_tools_master_ms_tools_recei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m13',
            options={},
        ),
    ]
