# Generated by Django 2.0.7 on 2020-01-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_machine_tools_mdescription_tooling1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp_details',
        ),
        migrations.DeleteModel(
            name='MG18',
        ),
    ]
