# Generated by Django 2.0.7 on 2020-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20200314_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_master',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam_master',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='examdoc/'),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='exam_sno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='join_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='oral_desc',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='prac_desc',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='pramedak_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
