# Generated by Django 2.0.7 on 2019-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20191017_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='M11doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopsec', models.CharField(db_column='shopsec', max_length=50, null=True)),
                ('staff_no', models.CharField(db_column='staffno', max_length=50, null=True)),
                ('name', models.CharField(db_column='name', max_length=50, null=True)),
                ('month', models.CharField(db_column='month', max_length=50, null=True)),
                ('date', models.CharField(db_column='date', max_length=50, null=True)),
                ('in1', models.CharField(db_column='in', max_length=50, null=True)),
                ('out', models.CharField(db_column='out', max_length=50, null=True)),
                ('tot', models.CharField(db_column='total_time', max_length=50, null=True)),
                ('detail_no', models.CharField(db_column='IT_reasons', max_length=70, null=True)),
                ('idle_time', models.CharField(db_column='idle_time', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dpo',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
