# Generated by Django 2.0.7 on 2019-10-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_m1card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='m1card',
        ),
    ]
