# Generated by Django 2.0.7 on 2020-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_delete_dpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureno', models.CharField(default='0', max_length=50, null=True)),
                ('locotype', models.CharField(max_length=50, null=True)),
                ('orderno', models.CharField(max_length=10, null=True)),
                ('subject', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('copyto', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('date', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
