# Generated by Django 2.0.7 on 2019-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20191121_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m13',
            name='wo',
            field=models.CharField(blank=True, db_column='WO', max_length=15, null=True),
        ),
    ]
