# Generated by Django 2.0.7 on 2020-01-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20200124_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=10)),
                ('empname', models.CharField(blank=True, max_length=100, null=True)),
                ('shopsec', models.CharField(blank=True, max_length=20, null=True)),
                ('desgn', models.CharField(blank=True, max_length=20, null=True)),
                ('grp', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_code', models.CharField(blank=True, max_length=20, null=True)),
                ('card_details', models.CharField(db_column='CARD_DETAILS', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MG18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=30, null=True)),
                ('login_id', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('name_occupier', models.CharField(max_length=60, null=True)),
                ('address_occupier', models.CharField(max_length=300, null=True)),
                ('empcode', models.CharField(max_length=25, null=True)),
                ('nature_of_industry', models.CharField(max_length=110, null=True)),
                ('address_accident', models.CharField(max_length=300, null=True)),
                ('branch_at_accident', models.CharField(max_length=50, null=True)),
                ('name_injured', models.CharField(max_length=60, null=True)),
                ('address_injured', models.CharField(max_length=300, null=True)),
                ('insurance_no', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('age_last_birth', models.CharField(max_length=10, null=True)),
                ('occupation_of_injured', models.CharField(max_length=40, null=True)),
                ('accident_date', models.CharField(max_length=20, null=True)),
                ('accident_time', models.CharField(max_length=20, null=True)),
                ('hour_of_startwork', models.CharField(max_length=20, null=True)),
                ('cause', models.CharField(max_length=130, null=True)),
                ('cause_by_machine', models.CharField(max_length=10, null=True)),
                ('machine_part', models.CharField(max_length=100, null=True)),
                ('mach_mov_state', models.CharField(max_length=100, null=True)),
                ('injured_doing', models.CharField(max_length=100, null=True)),
                ('injury_nature', models.CharField(max_length=100, null=True)),
                ('injured_dayoff', models.CharField(max_length=10, null=True)),
                ('doctor_name', models.CharField(max_length=60, null=True)),
                ('name_evid', models.CharField(max_length=60, null=True)),
                ('inj_under_drink_drug', models.CharField(max_length=10, null=True)),
                ('wilful_disobedience', models.CharField(max_length=10, null=True)),
                ('wilful_removal', models.CharField(max_length=10, null=True)),
                ('how_accident', models.CharField(max_length=1000, null=True)),
                ('injury_location', models.CharField(max_length=100, null=True)),
                ('inj_return_to_work', models.CharField(max_length=100, null=True)),
                ('return_date', models.CharField(max_length=20, null=True)),
                ('return_time', models.CharField(max_length=20, null=True)),
                ('injured_died', models.CharField(max_length=10, null=True)),
                ('date_of_death', models.CharField(max_length=20, null=True)),
                ('insur_localoffice_name', models.CharField(max_length=100, null=True)),
                ('insur_dispensary_name', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=60, null=True)),
                ('receipt_date', models.CharField(max_length=20, null=True)),
                ('accident_no', models.CharField(max_length=20, null=True)),
                ('industry_no', models.CharField(max_length=20, null=True)),
                ('causation_no', models.CharField(max_length=20, null=True)),
                ('gender_1', models.CharField(max_length=15, null=True)),
                ('particulars', models.CharField(max_length=60, null=True)),
                ('investigation_date', models.CharField(max_length=20, null=True)),
                ('investigation_result', models.CharField(max_length=500, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
