# Generated by Django 2.0.7 on 2020-05-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_mg47_table1_mg47_table2'),
    ]

    operations = [
       
    ]
