# Generated by Django 2.0.7 on 2019-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_auto_20191121_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxleMachining',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bo_no', models.CharField(max_length=20, null=True)),
                ('bo_date', models.CharField(max_length=20, null=True)),
                ('pt_no', models.CharField(max_length=20, null=True)),
                ('bo_qty', models.CharField(max_length=20, null=True)),
                ('axle_no', models.CharField(max_length=20, null=True)),
                ('axle_make', models.CharField(max_length=20, null=True)),
                ('axle_heatcaseno', models.CharField(max_length=20, null=True)),
                ('loco_type', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('dispatch_to', models.CharField(max_length=20, null=True)),
                ('ustaxle', models.CharField(blank=True, max_length=20)),
                ('ustaxle_date', models.CharField(max_length=20, null=True)),
                ('ustaxle_status', models.CharField(max_length=20, null=True)),
                ('axlelength', models.CharField(blank=True, max_length=20)),
                ('journalaxle', models.CharField(blank=True, max_length=20)),
                ('throweraxle', models.CharField(blank=True, max_length=20)),
                ('wheelseataxle', models.CharField(blank=True, max_length=20)),
                ('gearseataxle', models.CharField(blank=True, max_length=20)),
                ('collaraxle', models.CharField(blank=True, max_length=20)),
                ('dateaxle', models.CharField(max_length=20, null=True)),
                ('bearingaxle', models.CharField(blank=True, max_length=20)),
                ('abutmentaxle', models.CharField(blank=True, max_length=20)),
                ('inspector_nameaxle', models.CharField(blank=True, max_length=20)),
                ('journal_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('wheelseat_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('gearseat_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('journal_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('wheelseat_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('gearseat_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('dispatch_status', models.BooleanField(default=False)),
                ('axlefitting_status', models.BooleanField(default=False)),
                ('axleinspection_status', models.BooleanField(default=False)),
                ('inspection_status', models.NullBooleanField()),
                ('dispatch_date', models.CharField(max_length=20, null=True)),
                ('axlep_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelMachining',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bo_no', models.CharField(max_length=20, null=True)),
                ('bo_date', models.CharField(max_length=20, null=True)),
                ('pt_no', models.CharField(max_length=20, null=True)),
                ('bo_qty', models.CharField(max_length=20, null=True)),
                ('wheel_no', models.CharField(max_length=20, null=True)),
                ('wheel_make', models.CharField(max_length=20, null=True)),
                ('wheel_heatcaseno', models.CharField(max_length=20, null=True)),
                ('loco_type', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('dispatch_to', models.CharField(max_length=20, null=True)),
                ('ustwhl', models.CharField(max_length=20, null=True)),
                ('ustwhl_date', models.CharField(max_length=20, null=True)),
                ('ustwhl_status', models.CharField(max_length=20, null=True)),
                ('hub_lengthwhl', models.CharField(max_length=20, null=True)),
                ('tread_diawhl', models.CharField(max_length=20, null=True)),
                ('rim_thicknesswhl', models.CharField(max_length=20, null=True)),
                ('bore_diawhl', models.CharField(max_length=20, null=True)),
                ('inspector_namewhl', models.CharField(max_length=20, null=True)),
                ('datewhl', models.CharField(max_length=20, null=True)),
                ('dispatch_status', models.BooleanField(default=False)),
                ('wheelfitting_status', models.BooleanField(default=False)),
                ('wheelinspection_status', models.BooleanField(default=False)),
                ('inspection_status', models.NullBooleanField()),
                ('dispatch_date', models.CharField(max_length=20, null=True)),
                ('wheelp_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AxleWheelMachining',
        ),
    ]
