# Generated by Django 2.0.7 on 2020-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_auto_20200314_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempQtysum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=4, max_digits=1000, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('l_fr', models.CharField(blank=True, db_column='L_FR', max_length=4, null=True)),
                ('l_to', models.CharField(blank=True, db_column='L_TO', max_length=4, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=4, max_digits=1000, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('rm_lf', models.CharField(blank=True, db_column='RM_LF', max_length=4, null=True)),
                ('rm_lt', models.CharField(blank=True, db_column='RM_LT', max_length=4, null=True)),
                ('dt_run', models.DateField(blank=True, db_column='DT_RUN', null=True)),
                ('cur_time', models.CharField(blank=True, db_column='CUR_TIME', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrap_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=4, max_digits=1000, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('pt_lf', models.CharField(blank=True, db_column='PT_LF', max_length=4, null=True)),
                ('pt_lt', models.CharField(blank=True, db_column='PT_LT', max_length=4, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=4, max_digits=1000, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('rm_lf', models.CharField(blank=True, db_column='RM_LF', max_length=4, null=True)),
                ('rm_lt', models.CharField(blank=True, db_column='RM_LT', max_length=4, null=True)),
                ('rem', models.CharField(blank=True, db_column='REM', max_length=10, null=True)),
                ('v_qty', models.CharField(blank=True, db_column='V_QTY', max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='axle_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='inspect_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
