# Generated by Django 2.0.7 on 2020-04-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_tempm5docnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='logbook_work_desc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=20)),
                ('Work_desc', models.CharField(max_length=200)),
                ('Shop_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='logbook_record',
            old_name='job_booked',
            new_name='m5glsno',
        ),
        migrations.RenameField(
            model_name='logbook_record',
            old_name='remarks',
            new_name='opnno',
        ),
        migrations.AddField(
            model_name='empmast',
            name='appointmentdate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='office_orderno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='date',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='flag',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='last_modified',
            field=models.CharField(blank=True, default=0, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='login_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='opn_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='shift',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='shop_sec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='staffname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='stafftype',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='timein',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='timeout',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logbook_record',
            name='workorderno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roster1',
            name='stafftype',
            field=models.CharField(blank=True, db_column='stafftype', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logbook_record',
            name='attandance',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
