# Generated by Django 2.0.7 on 2019-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_m23doc_mg7'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmast',
            name='idcard_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
