# Generated by Django 2.0.7 on 2020-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_dpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med1',
            fields=[
                ('recordno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empno', models.CharField(max_length=50, null=True)),
                ('empname', models.CharField(max_length=20, null=True)),
                ('empdesignation', models.CharField(max_length=50, null=True)),
                ('empdepartment', models.CharField(max_length=50, null=True)),
                ('doctorid', models.CharField(max_length=50, null=True)),
                ('doctorname', models.CharField(max_length=50, null=True)),
                ('doctordesignation', models.CharField(max_length=50, null=True)),
                ('stationempno', models.CharField(max_length=50, null=True)),
                ('suffingfrom', models.CharField(max_length=50, null=True)),
                ('effectdate', models.CharField(max_length=50, null=True)),
                ('update', models.CharField(max_length=50, null=True)),
                ('dutyfordays', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='m11',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mg10',
            name='formid',
        ),
        migrations.RemoveField(
            model_name='mg11',
            name='formid',
        ),
        migrations.AddField(
            model_name='m11',
            name='in_date',
            field=models.CharField(blank=True, db_column='IN_DATE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='m11',
            name='out_date',
            field=models.CharField(blank=True, db_column='OUT_DATE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='m11',
            name='shift',
            field=models.CharField(blank=True, db_column='SHIFT_TYPE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='letter_no',
            field=models.CharField(blank=True, db_column='LETTET_NO', default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='subject',
            field=models.CharField(blank=True, db_column='SUBJECT', default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='m22',
            name='update',
            field=models.CharField(blank=True, db_column='UPDATE', default=0, max_length=20, null=True),
        ),
    ]
