# Generated by Django 2.0.7 on 2020-01-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_emp_details_mg18'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_part', models.CharField(blank=True, db_column='PP_PART', max_length=8, null=True)),
                ('epc', models.CharField(blank=True, db_column='QTY', max_length=2, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='EPC', decimal_places=3, max_digits=9, null=True)),
            ],
        ),
    ]
