# Generated by Django 2.0.7 on 2020-05-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_qtysumtemp_qtysumtemp1_qtysumtemp2'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtysumTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=10, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('ptlf', models.CharField(blank=True, db_column='PTLF', max_length=4, null=True)),
                ('ptlt', models.CharField(blank=True, db_column='PTLT', max_length=4, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=3, max_digits=10, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('rmlf', models.CharField(blank=True, db_column='RMLF', max_length=4, null=True)),
                ('rmlt', models.CharField(blank=True, db_column='RMLT', max_length=4, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=10, null=True)),
                ('qty_loco', models.CharField(blank=True, db_column='QTY_LOCO', max_length=20, null=True)),
                ('dt_run', models.DateField(blank=True, db_column='DT_RUN', null=True)),
                ('cur_time', models.CharField(blank=True, db_column='CUR_TIME', max_length=40, null=True)),
            ],
            options={
                'db_table': 'QTYSUM_TEMP',
            },
        ),
        migrations.CreateModel(
            name='QtysumTemp1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=10, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('l_fr', models.CharField(blank=True, db_column='L_FR', max_length=4, null=True)),
                ('l_to', models.CharField(blank=True, db_column='L_TO', max_length=4, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=3, max_digits=10, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('rm_lf', models.CharField(blank=True, db_column='RM_LF', max_length=4, null=True)),
                ('rm_lt', models.CharField(blank=True, db_column='RM_LT', max_length=4, null=True)),
                ('dt_run', models.DateField(blank=True, db_column='DT_RUN', null=True)),
                ('cur_time', models.CharField(blank=True, db_column='CUR_TIME', max_length=40, null=True)),
            ],
            options={
                'db_table': 'QTYSUM_TEMP1',
            },
        ),
        migrations.CreateModel(
            name='QtysumTemp2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partno', models.CharField(blank=True, db_column='PARTNO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=10, null=True)),
                ('shop_ut', models.CharField(blank=True, db_column='SHOP_UT', max_length=2, null=True)),
                ('pt_lf', models.CharField(blank=True, db_column='PT_LF', max_length=4, null=True)),
                ('pt_lt', models.CharField(blank=True, db_column='PT_LT', max_length=4, null=True)),
                ('rm_part', models.CharField(blank=True, db_column='RM_PART', max_length=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=3, max_digits=10, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('rm_lf', models.CharField(blank=True, db_column='RM_LF', max_length=4, null=True)),
                ('rm_lt', models.CharField(blank=True, db_column='RM_LT', max_length=4, null=True)),
                ('dt_run', models.DateField(blank=True, db_column='DT_RUN', null=True)),
                ('cur_time', models.CharField(blank=True, db_column='CUR_TIME', max_length=40, null=True)),
            ],
            options={
                'db_table': 'QTYSUM_TEMP2',
            },
        ),
    ]
