# Generated by Django 2.0.7 on 2020-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_mg47_table1_mg47_table2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m15',
            name='login_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
