# Generated by Django 2.0.7 on 2019-12-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_m4hw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M4HW',
        ),
    ]
