# Generated by Django 2.0.7 on 2019-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_auto_20191119_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG33examMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=30, null=True)),
                ('prac_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
