# Generated by Django 2.0.7 on 2019-10-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_delete_m1card'),
    ]

    operations = [
        migrations.CreateModel(
            name='barrelfirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locotype', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
