# Generated by Django 2.0.7 on 2019-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_auto_20191120_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_master',
            name='exam_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam_master',
            name='oral_max',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='exam_master',
            name='prac_max',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
