# Generated by Django 2.0.7 on 2020-03-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_auto_20200317_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptld',
            options={},
        ),
    ]
