# Generated by Django 2.0.7 on 2020-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_auto_20200721_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='m13tmp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_no', models.CharField(blank=True, db_column='BO_NO', max_length=7, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=8, null=True)),
                ('ep_type', models.CharField(blank=True, db_column='EP_TYPE', max_length=2, null=True)),
                ('pm_no', models.CharField(blank=True, db_column='PM_NO', max_length=4, null=True)),
                ('org_batch', models.CharField(blank=True, db_column='ORG_BATCH', max_length=7, null=True)),
                ('brn_no', models.CharField(blank=True, db_column='BRN_NO', max_length=8, null=True)),
                ('batch_qty', models.CharField(blank=True, db_column='BATCH_QTY', max_length=8, null=True)),
                ('batch_type', models.CharField(blank=True, db_column='BATCH_TYPE', max_length=1, null=True)),
                ('seq', models.CharField(blank=True, db_column='SEQ', max_length=3, null=True)),
                ('loco_fr', models.CharField(blank=True, db_column='LOCO_FR', max_length=4, null=True)),
                ('loco_to', models.CharField(blank=True, db_column='LOCO_TO', max_length=4, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('b_expl_dt', models.CharField(blank=True, db_column='B_EXPL_DT', max_length=10, null=True)),
                ('bo_updt_dt', models.CharField(blank=True, db_column='BO_UPDT_DT', max_length=10, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=3, null=True)),
            ],
        ),
    ]
