# Generated by Django 2.0.7 on 2019-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_auto_20191120_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mg33new',
            old_name='acc_date',
            new_name='exam_code',
        ),
        migrations.RenameField(
            model_name='mg33new',
            old_name='ticketno',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='mg33new',
            old_name='place',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='oral_desc',
        ),
        migrations.RemoveField(
            model_name='mg33new',
            name='prac_desc',
        ),
        migrations.AddField(
            model_name='mg33new',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mg33new',
            name='staff_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
