# Generated by Django 2.0.7 on 2019-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_auto_20191122_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='M27TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(max_length=20, null=True)),
                ('staff_no', models.CharField(max_length=20, null=True)),
                ('desg', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('rate', models.CharField(max_length=20, null=True)),
                ('wo_no', models.CharField(max_length=20, null=True)),
                ('ofc_date', models.CharField(max_length=20, null=True)),
                ('wo_date', models.CharField(max_length=20, null=True)),
                ('tot_hrs', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
