# Generated by Django 2.0.7 on 2019-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_auto_20191026_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m20new',
            name='alt_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
