# Generated by Django 2.0.7 on 2020-02-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_t_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2Docnew1',
        ),
    ]
