# Generated by Django 2.0.7 on 2020-02-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_delete_m2docnew1'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2Docnew1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scl_cl', models.CharField(blank=True, db_column='SCL_CL', max_length=1, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=7, null=True)),
                ('assly_no', models.CharField(blank=True, db_column='ASSLY_NO', max_length=8, null=True)),
                ('f_shopsec', models.CharField(blank=True, db_column='F_SHOPSEC', max_length=4, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=8, null=True)),
                ('ptc', models.CharField(blank=True, db_column='PTC', max_length=1, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=16, null=True)),
                ('rc_st_wk', models.CharField(blank=True, db_column='RC_ST_WK', max_length=4, null=True)),
                ('rm_partno', models.CharField(blank=True, db_column='RM_PARTNO', max_length=8, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=3, max_digits=8, null=True)),
                ('rm_ptc', models.CharField(blank=True, db_column='RM_PTC', max_length=1, null=True)),
                ('cut_shear', models.CharField(blank=True, db_column='CUT_SHEAR', max_length=8, null=True)),
                ('m2sln', models.DecimalField(blank=True, db_column='M2SLN', decimal_places=0, max_digits=6, null=True)),
                ('m2prtdt', models.CharField(blank=True, db_column='M2PRTDT', max_length=10, null=True)),
                ('seq', models.DecimalField(blank=True, db_column='SEQ', decimal_places=0, max_digits=3, null=True)),
                ('brn_no', models.DecimalField(blank=True, db_column='BRN_NO', decimal_places=0, max_digits=5, null=True)),
                ('m4_no', models.DecimalField(blank=True, db_column='M4_NO', decimal_places=0, max_digits=6, null=True)),
                ('epc', models.CharField(blank=True, db_column='EPC', max_length=2, null=True)),
                ('version', models.CharField(blank=True, db_column='VERSION', max_length=1, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('mark', models.CharField(blank=True, db_column='MARK', max_length=1, null=True)),
                ('del_fl', models.CharField(blank=True, db_column='DEL_FL', max_length=1, null=True)),
                ('epc_old', models.CharField(blank=True, db_column='EPC_OLD', max_length=1, null=True)),
            ],
            options={
                'db_table': 'M2DOCNEW1',
            },
        ),
    ]
