# Generated by Django 2.0.7 on 2019-12-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_m4hw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2HW',
        ),
    ]
