# Generated by Django 2.0.7 on 2020-03-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_auto_20200319_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptld',
            name='drgno',
            field=models.CharField(blank=True, db_column='DRGNO', max_length=18, null=True),
        ),
        migrations.AlterModelTable(
            name='ptld',
            table=None,
        ),
    ]
