# Generated by Django 2.0.7 on 2019-11-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_auto_20191119_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mg33new',
            old_name='ticketno',
            new_name='staff_no',
        ),
    ]
