# Generated by Django 2.0.7 on 2019-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_empmast_miscellsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxleWheelMachining',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bo_no', models.CharField(max_length=20, null=True)),
                ('bo_date', models.CharField(max_length=20, null=True)),
                ('wheel_no', models.CharField(max_length=20, null=True)),
                ('wheel_make', models.CharField(max_length=20, null=True)),
                ('wheel_heatcaseno', models.CharField(max_length=20, null=True)),
                ('axle_no', models.CharField(max_length=20, null=True)),
                ('axle_make', models.CharField(max_length=20, null=True)),
                ('axle_heatcaseno', models.CharField(max_length=20, null=True)),
                ('loco_type', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('dispatch_to', models.CharField(max_length=20, null=True)),
                ('ustaxle', models.CharField(blank=True, max_length=20)),
                ('axlelength', models.CharField(blank=True, max_length=20)),
                ('journalaxle', models.CharField(blank=True, max_length=20)),
                ('throweraxle', models.CharField(blank=True, max_length=20)),
                ('wheelseataxle', models.CharField(blank=True, max_length=20)),
                ('gearseataxle', models.CharField(blank=True, max_length=20)),
                ('collaraxle', models.CharField(blank=True, max_length=20)),
                ('dateaxle', models.DateField(null=True)),
                ('bearingaxle', models.CharField(blank=True, max_length=20)),
                ('abutmentaxle', models.CharField(blank=True, max_length=20)),
                ('inspector_nameaxle', models.CharField(blank=True, max_length=20)),
                ('journal_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('wheelseat_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('gearseat_surfacefinishGE', models.CharField(blank=True, max_length=20)),
                ('journal_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('wheelseat_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('gearseat_surfacefinishFE', models.CharField(blank=True, max_length=20)),
                ('batch_order_no', models.CharField(max_length=20, null=True)),
                ('ustwhl', models.CharField(max_length=20, null=True)),
                ('hub_lengthwhl', models.CharField(max_length=20, null=True)),
                ('tread_diawhl', models.CharField(max_length=20, null=True)),
                ('rim_thicknesswhl', models.CharField(max_length=20, null=True)),
                ('bore_diawhl', models.CharField(max_length=20, null=True)),
                ('inspector_namewhl', models.CharField(max_length=20, null=True)),
                ('datewhl', models.DateField(null=True)),
            ],
        ),
    ]
