# Generated by Django 2.0.7 on 2020-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_auto_20200527_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinionpressing',
            old_name='pinion_pressure',
            new_name='pinion_pressure_square_ram',
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='wheel_de_pressure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='dispatch_check',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='dispatch_check_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_axle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_axle_location',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_back_lash',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_gearcase_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_gearcase_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_horizontal_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_horizontal_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_secondary_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_vertical_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='first_vertical_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='gear_case_oil',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='h_plate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='inspect_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='loco_paper',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='locopaper_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='lowering_check',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='lowering_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='motor_check',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='motor_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_axle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_axle_location',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_back_lash',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_gearcase_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_gearcase_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_horizontal_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_horizontal_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_secondary_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_vertical_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='second_vertical_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_axle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_axle_location',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_back_lash',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_gearcase_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_gearcase_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_horizontal_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_horizontal_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_secondary_coilspring_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_vertical_l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='third_vertical_r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='torque_support',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='wheel_set_guide',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='pinion_pressure_triangle_glycerin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='pinion_teeth_dist',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
