# Generated by Django 2.0.7 on 2019-11-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_m27timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='M21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('shop_sec', models.CharField(blank=True, max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('desgn', models.CharField(blank=True, max_length=10, null=True)),
                ('cat', models.CharField(blank=True, max_length=10, null=True)),
                ('in1', models.CharField(blank=True, max_length=10, null=True)),
                ('out', models.CharField(blank=True, max_length=10, null=True)),
                ('in2', models.CharField(blank=True, max_length=10, null=True)),
                ('out2', models.CharField(blank=True, max_length=10, null=True)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MG6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_no', models.CharField(blank=True, db_column='TOOL_NO', max_length=8, null=True)),
                ('tool_des', models.CharField(blank=True, db_column='TOOL_DES', max_length=50, null=True)),
                ('ticket_no', models.CharField(blank=True, db_column='TICKET_NO', max_length=12, null=True)),
                ('date_of_damage', models.CharField(blank=True, db_column='DATE_OF_DAMAGE', max_length=20, null=True)),
                ('machine_no', models.CharField(blank=True, db_column='MACHINE_NO', max_length=4, null=True)),
                ('cd_no', models.CharField(blank=True, db_column='CD_NO', max_length=8, null=True)),
                ('cause_of_damage', models.CharField(blank=True, db_column='CAUSE_OF_DAMAGE', max_length=70, null=True)),
                ('last_modified', models.CharField(blank=True, db_column='LAST_MODIFIED', max_length=50, null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
                ('shop_suprintendent', models.CharField(blank=True, db_column='SHOP_SUPRINTENDENT', max_length=15, null=True)),
                ('sec_chargeman', models.CharField(blank=True, db_column='SEC_CHARGEMAN', max_length=15, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=60, null=True)),
            ],
            options={
                'db_table': 'MG6',
            },
        ),
    ]
