# Generated by Django 2.0.7 on 2019-10-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_axlewheelmachining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m14m4',
            options={},
        ),
    ]
