# Generated by Django 2.0.7 on 2020-02-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_m2docnew1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2Docnew1',
        ),
    ]
