# Generated by Django 2.0.7 on 2019-11-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_auto_20191119_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mg33new',
            name='empno',
        ),
    ]
