# Generated by Django 2.0.7 on 2020-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_auto_20200601_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='axle_box_clearance',
            new_name='axialplay_de',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='axle_box_make',
            new_name='axialplay_nde',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='axle_box_no',
            new_name='axle_box_clearancede',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='suspension_bearing_de_make',
            new_name='axle_box_clearancende',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='suspension_bearing_de_no',
            new_name='axle_box_makede',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='suspension_bearing_nde_make',
            new_name='axle_box_makende',
        ),
        migrations.RenameField(
            model_name='axlewheelpressing',
            old_name='suspension_bearing_nde_no',
            new_name='axle_box_node',
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='axle_box_nonde',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='msu_bearing_de_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='msu_bearing_nde_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='wheel_distance',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
