# Generated by Django 2.0.7 on 2019-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_bogieassembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG22new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updt_date', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_sec', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=10, null=True)),
                ('ticketno', models.CharField(blank=True, max_length=10, null=True)),
                ('acc_Date', models.DateField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_neg', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_y_neg', models.CharField(blank=True, max_length=100, null=True)),
                ('equip_check', models.CharField(blank=True, max_length=100, null=True)),
                ('suggestions', models.CharField(blank=True, max_length=100, null=True)),
                ('bgc', models.CharField(blank=True, max_length=100, null=True)),
                ('bgc2', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_sup', models.CharField(blank=True, max_length=100, null=True)),
                ('charegeman', models.CharField(blank=True, max_length=100, null=True)),
                ('mistry', models.CharField(blank=True, max_length=100, null=True)),
                ('c1', models.CharField(blank=True, max_length=100, null=True)),
                ('c2', models.CharField(blank=True, max_length=100, null=True)),
                ('c3', models.CharField(blank=True, max_length=100, null=True)),
                ('c4', models.CharField(blank=True, max_length=100, null=True)),
                ('a1', models.CharField(blank=True, max_length=100, null=True)),
                ('a3', models.CharField(blank=True, max_length=100, null=True)),
                ('ssfo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MG22new',
            },
        ),
    ]
