# Generated by Django 2.0.7 on 2019-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_m21_mg6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m13',
            name='m13_date',
            field=models.CharField(blank=True, db_column='M13_DATE', max_length=15, null=True),
        ),
    ]
