# Generated by Django 2.0.7 on 2019-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0009_auto_20191009_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='m14m4',
            name='epc_old1',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
