# Generated by Django 2.0.7 on 2019-11-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0009_mg22new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mg22new',
            old_name='charegeman',
            new_name='a2',
        ),
        migrations.AddField(
            model_name='mg22new',
            name='chargeman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
