# Generated by Django 2.0.7 on 2019-12-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0009_m2hw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2hw',
            name='asmlyDesc',
            field=models.CharField(db_column='ASMLYDESC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='operationDescription',
            field=models.CharField(db_column='OPERATIONDESCRIPTION', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='partDescription',
            field=models.CharField(db_column='PARTDESCRIPTION', max_length=200, null=True),
        ),
    ]
