# Generated by Django 2.0.7 on 2019-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_auto_20191219_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prtdt', models.DateField(db_column='PRINTDATE', max_length=20)),
                ('doc_no', models.CharField(db_column='DOCNO', max_length=100, null=True)),
                ('part_no', models.CharField(db_column='PARTNO', max_length=50, null=True)),
                ('wo_no', models.CharField(db_column='WONO', max_length=50, null=True)),
                ('brn_no', models.CharField(db_column='BRNNO', max_length=50, null=True)),
                ('qty', models.CharField(db_column='ORDERQUANTITY', max_length=50, null=True)),
                ('end_prod', models.CharField(db_column='ENDPRODUCT', max_length=50, null=True)),
                ('epdes', models.CharField(db_column='EPDESC', max_length=100, null=True)),
                ('shop_section_temp', models.CharField(db_column='SHOPSECTION', max_length=50, null=True)),
                ('partdes', models.CharField(db_column='PARTDES', max_length=50, null=True)),
                ('drgno', models.CharField(db_column='DRAWINGNO', max_length=100, null=True)),
                ('batch_type', models.CharField(db_column='BATCHTYPE', max_length=50, null=True)),
                ('received_mat', models.CharField(db_column='RECEVMAT', max_length=50, null=True)),
                ('issued_qty', models.CharField(db_column='ISSUEDQTY', max_length=50, null=True)),
                ('received_qty', models.CharField(blank=True, db_column='RECEIVEQTY', max_length=50, null=True)),
                ('laser_pst', models.CharField(blank=True, db_column='LASERPST', max_length=50, null=True)),
                ('line', models.CharField(db_column='LINE', max_length=100, null=True)),
                ('closing_bal', models.CharField(db_column='CLOSINGBAL', max_length=50, null=True)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=50, null=True)),
                ('posted_date', models.CharField(db_column='POSTEDDATE', max_length=50, null=True)),
                ('wardkp_date', models.CharField(db_column='HARDKEEPARDATE', max_length=50, null=True)),
                ('shopsup_date', models.CharField(db_column='SHOPSUPDATE', max_length=50, null=True)),
                ('posted1_date', models.CharField(db_column='SUPPOSTEDDATE', max_length=50, null=True)),
                ('number', models.CharField(db_column='UNIQUENUM', max_length=50, null=True)),
            ],
        ),
    ]
