# Generated by Django 2.0.7 on 2019-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_m14m4_epc_old1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m14m4',
            name='epc_old1',
        ),
    ]
