# Generated by Django 2.0.7 on 2019-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_auto_20191101_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mg22new',
            name='acc_Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
