# Generated by Django 2.0.7 on 2020-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_m2docnew1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oprn_audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updt_by', models.CharField(blank=True, db_column='UPDT_BY', max_length=50, null=True)),
                ('updt_time', models.CharField(blank=True, db_column='UPDT_TIME', max_length=40, null=True)),
                ('updt_col', models.CharField(blank=True, db_column='UPDT_COL', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Oprn_audit',
            },
        ),
    ]
