# Generated by Django 2.0.7 on 2019-11-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0011_auto_20191125_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bogieassembly',
            name='in_qty',
        ),
    ]
