# Generated by Django 2.0.7 on 2019-12-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0011_mtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtest',
        ),
    ]
