# Generated by Django 2.0.7 on 2020-02-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0011_oprn_audit'),
    ]

    operations = [
    ]
