# Generated by Django 2.0.7 on 2019-11-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_auto_20191101_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='cstr_buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_part', models.CharField(blank=True, max_length=10, null=True)),
                ('cp_part', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
