# Generated by Django 2.0.7 on 2019-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_remove_bogieassembly_in_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinionpressing',
            name='in_qty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='out_qty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
