# Generated by Django 2.0.7 on 2019-10-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_auto_20191009_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='m14m4',
            name='laser_pst',
            field=models.DateField(blank=True, db_column='LASER_PST', null=True),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='posted1_date',
            field=models.DateField(blank=True, db_column='POSTED1_DATE', default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='posted_date',
            field=models.DateField(blank=True, db_column='POSTED_DATE', default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='shopsup_date',
            field=models.DateField(blank=True, db_column='SHOPSUP_DATE', default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='wardkp_date',
            field=models.DateField(blank=True, db_column='WARDKP_DATE', default=datetime.date.today),
        ),
    ]
