# Generated by Django 2.0.7 on 2020-02-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_auto_20200208_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m14m4new1',
            name='prtdt',
            field=models.CharField(blank=True, db_column='PRTDT', max_length=10, null=True),
        ),
    ]
