# Generated by Django 2.0.7 on 2019-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_delete_mtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2hw',
            name='causesofHW',
            field=models.CharField(db_column='CAUSESOFHW', max_length=50, null=True),
        ),
    ]
