# Generated by Django 2.0.7 on 2019-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_m2hw_causesofhw'),
    ]

    operations = [
        migrations.AddField(
            model_name='m4hw',
            name='causesofHW',
            field=models.CharField(db_column='CAUSESOFHW', max_length=50, null=True),
        ),
    ]
