# Generated by Django 2.0.7 on 2019-10-09 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_auto_20191009_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m14m4',
            name='laser_pst',
            field=models.DateField(blank=True, db_column='LASER_PST', default=datetime.date.today),
        ),
    ]
