# Generated by Django 2.0.7 on 2019-11-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_auto_20191126_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='m3a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('shop_sec', models.CharField(blank=True, max_length=4, null=True)),
                ('item', models.CharField(blank=True, max_length=35, null=True)),
                ('part_no', models.CharField(blank=True, max_length=8, null=True)),
                ('drgno', models.CharField(blank=True, max_length=15, null=True)),
                ('C_Dno', models.CharField(blank=True, max_length=8, null=True)),
                ('wo_no', models.CharField(blank=True, max_length=7, null=True)),
                ('qty_ordr', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('qty_comp', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('as_this_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('sign', models.CharField(blank=True, max_length=50, null=True)),
                ('desgn', models.CharField(blank=True, max_length=10, null=True)),
                ('comp_part_full', models.CharField(blank=True, max_length=15, null=True)),
                ('cost_book_yesno', models.CharField(blank=True, max_length=15, null=True)),
                ('dspc', models.CharField(blank=True, max_length=100, null=True)),
                ('m3a_date', models.CharField(blank=True, max_length=20, null=True)),
                ('est_cost', models.CharField(blank=True, max_length=20, null=True)),
                ('deb_against', models.CharField(blank=True, max_length=20, null=True)),
                ('ep_code', models.CharField(blank=True, max_length=2, null=True)),
                ('loco_fr', models.CharField(blank=True, max_length=4, null=True)),
                ('loco_to', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, max_length=4, null=True)),
                ('instrument_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_des', models.CharField(blank=True, max_length=50, null=True)),
                ('type_mme', models.CharField(blank=True, max_length=50, null=True)),
                ('least_count', models.FloatField(blank=True, max_length=50, null=True)),
                ('calibration_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.CharField(blank=True, max_length=50, null=True)),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mgrreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, max_length=4, null=True)),
                ('instrument_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_des', models.CharField(blank=True, max_length=50, null=True)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('periodicity_check', models.CharField(blank=True, max_length=50, null=True)),
                ('date_calibration', models.CharField(blank=True, max_length=50, null=True)),
                ('calibration_status', models.CharField(blank=True, max_length=50, null=True)),
                ('calibration_due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
