# Generated by Django 2.0.7 on 2019-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_cstr_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='axlewheelmachining',
            name='inspection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='axlewheelpressing',
            name='inspection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bogieassembly',
            name='inspection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='inspection_status',
            field=models.BooleanField(default=False),
        ),
    ]
