# Generated by Django 2.0.7 on 2019-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0014_auto_20191101_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axlewheelmachining',
            name='dateaxle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='axlewheelmachining',
            name='datewhl',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
