# Generated by Django 2.0.7 on 2020-02-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0014_hwm5inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwm5inbox',
            name='at',
            field=models.CharField(blank=True, db_column='AT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='brn_no',
            field=models.CharField(blank=True, db_column='BRN_NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='del_fl',
            field=models.CharField(blank=True, db_column='DEL_FL', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='des',
            field=models.CharField(blank=True, db_column='DES', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='epc',
            field=models.CharField(blank=True, db_column='EPC', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='ib_no',
            field=models.CharField(blank=True, db_column='IB_NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='lc_no',
            field=models.CharField(blank=True, db_column='LC_NO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m2sln',
            field=models.CharField(blank=True, db_column='M2SLN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m4_no',
            field=models.CharField(blank=True, db_column='M4_NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m5glsn',
            field=models.CharField(blank=True, db_column='M5GLSN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='no_off',
            field=models.CharField(blank=True, db_column='NO_OFF', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okcpm',
            field=models.CharField(blank=True, db_column='OKCPM', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okjbs',
            field=models.CharField(blank=True, db_column='OKJBS', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okmrq',
            field=models.CharField(blank=True, db_column='OKMRQ', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okopn',
            field=models.CharField(blank=True, db_column='OKOPN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okptc',
            field=models.CharField(blank=True, db_column='OKPTC', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='oksplit',
            field=models.CharField(blank=True, db_column='OKSPLIT', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='oksslc',
            field=models.CharField(blank=True, db_column='OKSSLC', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='opn',
            field=models.CharField(blank=True, db_column='OPN', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='opn_desc',
            field=models.CharField(blank=True, db_column='OPN_DESC', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='opndesc',
            field=models.CharField(blank=True, db_column='OPNDESC', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='org_brnno',
            field=models.CharField(blank=True, db_column='ORG_BRNNO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='pa',
            field=models.CharField(blank=True, db_column='PA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='plregno',
            field=models.CharField(blank=True, db_column='PLREGNO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='print_ctrl',
            field=models.CharField(blank=True, db_column='PRINT_CTRL', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='qty_ord',
            field=models.CharField(blank=True, db_column='QTY_ORD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='remarks',
            field=models.CharField(blank=True, db_column='REMARKS', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_desc',
            field=models.CharField(blank=True, db_column='RM_DESC', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_qty',
            field=models.CharField(blank=True, db_column='RM_QTY', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_ut',
            field=models.CharField(blank=True, db_column='RM_UT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='scl_cl',
            field=models.CharField(blank=True, db_column='SCL_CL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='sel_sw',
            field=models.CharField(blank=True, db_column='SEL_SW', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='sel_sw_hod',
            field=models.CharField(blank=True, db_column='SEL_SW_HOD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='status',
            field=models.CharField(blank=True, db_column='STATUS', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='usr_cd',
            field=models.CharField(blank=True, db_column='USR_CD', max_length=10, null=True),
        ),
    ]
