# Generated by Django 2.0.7 on 2019-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0014_m4hw_causesofhw'),
    ]

    operations = [
        migrations.CreateModel(
            name='mg10',
            fields=[
                ('sno', models.AutoField(db_column='SL.No', primary_key=True, serialize=False)),
                ('formid', models.CharField(db_column='FORM_ID', max_length=30, null=True)),
                ('date', models.CharField(db_column='DATE', max_length=30, null=True)),
                ('month', models.CharField(db_column='MONTH', max_length=30, null=True)),
                ('shop_sec', models.CharField(db_column='SHOPSEC', max_length=20, null=True)),
                ('ticket_no', models.CharField(db_column='TICKET_NO', max_length=20, null=True)),
                ('name', models.CharField(db_column='name', max_length=30, null=True)),
                ('payrate', models.CharField(db_column='RATE_PAY', max_length=20, null=True)),
                ('cat', models.CharField(db_column='CATEGORY', max_length=30, null=True)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=40, null=True)),
                ('eiwdate', models.CharField(db_column='EIW_DATE', max_length=50, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LAST_MODIFIED', null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mg11',
            fields=[
                ('sno', models.AutoField(db_column='SL.No', primary_key=True, serialize=False)),
                ('formid', models.CharField(db_column='FORM_ID', max_length=30, null=True)),
                ('date', models.CharField(db_column='DATE', max_length=30, null=True)),
                ('month', models.CharField(db_column='MONTH', max_length=30, null=True)),
                ('shop_sec', models.CharField(db_column='SHOPSEC', max_length=20, null=True)),
                ('ticket_no', models.CharField(db_column='TICKET_NO', max_length=20, null=True)),
                ('name', models.CharField(db_column='name', max_length=30, null=True)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=40, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LAST_MODIFIED', null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mg11doc',
            fields=[
                ('sno', models.AutoField(db_column='SL.No', primary_key=True, serialize=False)),
                ('formid', models.CharField(db_column='FORM_ID', max_length=30, null=True)),
                ('date', models.CharField(db_column='DATE', max_length=30, null=True)),
                ('month', models.CharField(db_column='MONTH', max_length=30, null=True)),
                ('shop_sec', models.CharField(db_column='SHOPSEC', max_length=20, null=True)),
                ('ticket_no', models.CharField(db_column='TICKET_NO', max_length=20, null=True)),
                ('name', models.CharField(db_column='name', max_length=30, null=True)),
                ('remarks', models.CharField(db_column='REMARKS', max_length=40, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LAST_MODIFIED', null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
            ],
        ),
    ]
