# Generated by Django 2.0.7 on 2019-10-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0014_auto_20191009_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m14m4',
            name='laser_pst',
            field=models.CharField(blank=True, db_column='LASER_PST', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='posted1_date',
            field=models.CharField(blank=True, db_column='POSTED1_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='posted_date',
            field=models.CharField(blank=True, db_column='POSTED_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='shopsup_date',
            field=models.CharField(blank=True, db_column='SHOPSUP_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='wardkp_date',
            field=models.CharField(blank=True, db_column='WARDKP_DATE', default=0, max_length=50),
        ),
    ]
