# Generated by Django 2.0.7 on 2019-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0015_mg10_mg11_mg11doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.DecimalField(decimal_places=0, max_digits=18)),
                ('empname', models.CharField(blank=True, max_length=100, null=True)),
                ('shopsec', models.CharField(blank=True, max_length=20, null=True)),
                ('desgn', models.CharField(blank=True, max_length=20, null=True)),
                ('grp', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileno', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
