# Generated by Django 2.0.7 on 2020-01-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0016_emp_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='M14HW11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(blank=True, db_column='DOC_CODE', max_length=2, null=True)),
                ('m14_no', models.CharField(blank=True, db_column='M14_NO', max_length=10, null=True)),
                ('m14_date', models.CharField(blank=True, db_column='M14_DT', max_length=15, null=True)),
                ('m13_no', models.CharField(blank=True, db_column='M13_REF', max_length=10, null=True)),
                ('m13_date', models.CharField(blank=True, db_column='M13_DT', max_length=15, null=True)),
                ('char_wo', models.CharField(blank=True, db_column='C_WORKORDER', max_length=8, null=True)),
                ('sl_no', models.DecimalField(blank=True, db_column='M13_SLNO', decimal_places=0, max_digits=5, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=7, null=True)),
                ('brn_no', models.DecimalField(blank=True, db_column='BRN_NO', decimal_places=0, max_digits=5, null=True)),
                ('epc', models.CharField(blank=True, db_column='EPC', max_length=2, null=True)),
                ('l_fr', models.CharField(blank=True, db_column='L_FR', max_length=4, null=True)),
                ('l_to', models.CharField(blank=True, db_column='L_TO', max_length=4, null=True)),
                ('pm_no', models.CharField(blank=True, db_column='PM_NO', max_length=5, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=8, null=True)),
                ('part_desc', models.CharField(blank=True, db_column='PART_DESC', max_length=30, null=True)),
                ('qty', models.DecimalField(blank=True, db_column='QTY', decimal_places=3, max_digits=10, null=True)),
                ('epc_old', models.CharField(blank=True, db_column='EPC_OLD', max_length=1, null=True)),
                ('reason', models.CharField(blank=True, db_column='REASON', max_length=100, null=True)),
                ('assly_no', models.CharField(blank=True, db_column='ASSLY_NO', max_length=8, null=True)),
                ('assly_desc', models.CharField(blank=True, db_column='ASSLY_DESC', max_length=30, null=True)),
                ('unit', models.DecimalField(blank=True, db_column='UNIT', decimal_places=0, max_digits=5, null=True)),
            ],
        ),
    ]
