# Generated by Django 2.0.7 on 2020-02-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0016_auto_20200211_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwm5inbox',
            name='at',
            field=models.CharField(blank=True, db_column='AT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='brn_no',
            field=models.CharField(blank=True, db_column='BRN_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='del_fl',
            field=models.CharField(blank=True, db_column='DEL_FL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='epc',
            field=models.CharField(blank=True, db_column='EPC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='epc_old',
            field=models.CharField(blank=True, db_column='EPC_OLD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='ib_no',
            field=models.CharField(blank=True, db_column='IB_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='l_fr',
            field=models.CharField(blank=True, db_column='L_FR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='l_to',
            field=models.CharField(blank=True, db_column='L_TO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='lc_no',
            field=models.CharField(blank=True, db_column='LC_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='lcnoold',
            field=models.CharField(blank=True, db_column='LCNOOLD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m13_no',
            field=models.CharField(blank=True, db_column='M13_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m2sln',
            field=models.CharField(blank=True, db_column='M2SLN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m4_no',
            field=models.CharField(blank=True, db_column='M4_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m5_cd',
            field=models.CharField(blank=True, db_column='M5_CD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='m5glsn',
            field=models.CharField(blank=True, db_column='M5GLSN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='n_shopsec',
            field=models.CharField(blank=True, db_column='N_SHOPSEC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='ncp_jbs',
            field=models.CharField(blank=True, db_column='NCP_JBS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='no_off',
            field=models.CharField(blank=True, db_column='NO_OFF', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okcpm',
            field=models.CharField(blank=True, db_column='OKCPM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okjbs',
            field=models.CharField(blank=True, db_column='OKJBS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okmrq',
            field=models.CharField(blank=True, db_column='OKMRQ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okopn',
            field=models.CharField(blank=True, db_column='OKOPN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='okptc',
            field=models.CharField(blank=True, db_column='OKPTC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='oksplit',
            field=models.CharField(blank=True, db_column='OKSPLIT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='oksslc',
            field=models.CharField(blank=True, db_column='OKSSLC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='opn',
            field=models.CharField(blank=True, db_column='OPN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='org_batch',
            field=models.CharField(blank=True, db_column='ORG_BATCH', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='org_brnno',
            field=models.CharField(blank=True, db_column='ORG_BRNNO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='pa',
            field=models.CharField(blank=True, db_column='PA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='plregno',
            field=models.CharField(blank=True, db_column='PLREGNO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='pr_shopsec',
            field=models.CharField(blank=True, db_column='PR_SHOPSEC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='print_ctrl',
            field=models.CharField(blank=True, db_column='PRINT_CTRL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='qty_ord',
            field=models.CharField(blank=True, db_column='QTY_ORD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_qty',
            field=models.CharField(blank=True, db_column='RM_QTY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_ut',
            field=models.CharField(blank=True, db_column='RM_UT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='scl_cl',
            field=models.CharField(blank=True, db_column='SCL_CL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='sel_sw',
            field=models.CharField(blank=True, db_column='SEL_SW', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='sel_sw_hod',
            field=models.CharField(blank=True, db_column='SEL_SW_HOD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='seq',
            field=models.CharField(blank=True, db_column='SEQ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='shop_sec',
            field=models.CharField(blank=True, db_column='SHOP_SEC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='shopsecold',
            field=models.CharField(blank=True, db_column='SHOPSECOLD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='sn',
            field=models.CharField(blank=True, db_column='SN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='status',
            field=models.CharField(blank=True, db_column='STATUS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='time_pcpls',
            field=models.CharField(blank=True, db_column='TIME_PCPLS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='tot_hrspls',
            field=models.CharField(blank=True, db_column='TOT_HRSPLS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='usr_cd',
            field=models.CharField(blank=True, db_column='USR_CD', max_length=50, null=True),
        ),
    ]
