# Generated by Django 2.0.7 on 2019-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0016_mg9complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(blank=True, max_length=20, null=True)),
                ('srno', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('shopsec', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_no', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('staff_name', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('auth', models.CharField(blank=True, max_length=50, null=True)),
                ('mwno', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('empno_shop_mang', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('date_shop_mang', models.CharField(blank=True, default=0, max_length=60, null=True)),
                ('empno_sse', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('date_sse', models.CharField(blank=True, default=0, max_length=60, null=True)),
                ('login_id', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('last_modified', models.CharField(blank=True, default=0, max_length=60, null=True)),
                ('psnt_date', models.CharField(blank=True, default=0, max_length=60, null=True)),
            ],
        ),
    ]
