# Generated by Django 2.0.7 on 2019-10-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0017_auto_20191010_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m14m4',
            name='laser_pst',
        ),
        migrations.RemoveField(
            model_name='m14m4',
            name='posted1_date',
        ),
        migrations.RemoveField(
            model_name='m14m4',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='m14m4',
            name='shopsup_date',
        ),
        migrations.RemoveField(
            model_name='m14m4',
            name='wardkp_date',
        ),
    ]
