# Generated by Django 2.0.7 on 2020-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0017_auto_20200211_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwm5inbox',
            name='assly_no',
            field=models.CharField(blank=True, db_column='ASSLY_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='batch_no',
            field=models.CharField(blank=True, db_column='BATCH_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='part_no',
            field=models.CharField(blank=True, db_column='PART_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hwm5inbox',
            name='rm_partno',
            field=models.CharField(blank=True, db_column='RM_PARTNO', max_length=50, null=True),
        ),
    ]
