# Generated by Django 2.0.7 on 2019-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0017_auto_20191104_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=8, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=25, null=True)),
                ('desgn', models.CharField(blank=True, db_column='DESIGNATION', max_length=20, null=True)),
                ('cat', models.CharField(blank=True, db_column='CATEGORY', max_length=10, null=True)),
                ('emp_type', models.CharField(blank=True, db_column='EMPLOYEE_TYPE', max_length=15, null=True)),
                ('no_of_days', models.CharField(blank=True, db_column='NO_OF_DAYS', max_length=8, null=True)),
                ('nature', models.CharField(blank=True, db_column='NATURE_OF_INJURY', max_length=50, null=True)),
                ('appr_datej', models.CharField(blank=True, db_column='APPROX_DATE_OF_JOINING', default='0', max_length=10, null=True)),
                ('current_date', models.CharField(blank=True, db_column='CURRENT_DATE', default='0', max_length=10, null=True)),
            ],
            options={
                'db_table': 'MG20',
            },
        ),
    ]
