# Generated by Django 2.0.7 on 2020-02-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0018_auto_20200211_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axlemachining',
            name='axle_heatcaseno',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='wheelmachining',
            name='wheel_heatcaseno',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
