# Generated by Django 2.0.7 on 2019-10-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0018_auto_20191010_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='m14m4',
            name='laser_pst',
            field=models.CharField(blank=True, db_column='LASER_PST', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='posted1_date',
            field=models.CharField(blank=True, db_column='POSTED1_DATE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='posted_date',
            field=models.CharField(blank=True, db_column='POSTED_DATE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='shopsup_date',
            field=models.CharField(blank=True, db_column='SHOPSUP_DATE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='m14m4',
            name='wardkp_date',
            field=models.CharField(blank=True, db_column='WARDKP_DATE', max_length=50, null=True),
        ),
    ]
