# Generated by Django 2.0.7 on 2020-01-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0018_m14hw11_loco_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intershop',
            fields=[
                ('shop_sec', models.CharField(blank=True, db_column='SHOPSEC', default=0, max_length=50, null=True)),
                ('staffNo', models.CharField(db_column='staffNo', max_length=20, primary_key=True, serialize=False)),
                ('staffName', models.CharField(db_column='staffNAME', max_length=50, null=True)),
                ('staffDesg', models.CharField(db_column='staffDesg', max_length=50, null=True)),
                ('reference_authority', models.CharField(db_column='REFERENCEAUTHORITY', max_length=100, null=True)),
                ('staffRate', models.CharField(blank=True, db_column='staffRate', max_length=50, null=True)),
                ('toshop_sec', models.CharField(blank=True, db_column='TOSHOPSEC', default=0, max_length=50, null=True)),
                ('date1', models.CharField(db_column='date1', max_length=20, null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGINID', max_length=10, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=5, null=True)),
                ('current_date', models.DateTimeField(blank=True, db_column='CURRENTDATE', null=True)),
            ],
            options={
                'db_table': 'Intershop',
            },
        ),
    ]
