# Generated by Django 2.0.7 on 2020-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_auto_20200212_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m5docnew1',
            name='m5prtdt',
            field=models.CharField(blank=True, db_column='M5PRTDT', max_length=10, null=True),
        ),
    ]
