# Generated by Django 2.0.7 on 2020-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_intershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanctionSSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopsec', models.CharField(blank=True, max_length=4, null=True)),
                ('desig', models.CharField(blank=True, max_length=50, null=True)),
                ('sanc', models.CharField(blank=True, max_length=5, null=True)),
                ('login_id', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('last_modified', models.CharField(blank=True, default=0, max_length=50, null=True)),
            ],
        ),
    ]
