# Generated by Django 2.0.7 on 2019-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_auto_20191010_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='M5DOCnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scl_cl', models.CharField(blank=True, db_column='SCL_CL', max_length=1, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=7, null=True)),
                ('assly_no', models.CharField(blank=True, db_column='ASSLY_NO', max_length=8, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=8, null=True)),
                ('m2slno', models.DecimalField(blank=True, db_column='M2SLNO', decimal_places=0, max_digits=6, null=True)),
                ('rm_partno', models.CharField(blank=True, db_column='RM_PARTNO', max_length=8, null=True)),
                ('rm_ut', models.CharField(blank=True, db_column='RM_UT', max_length=2, null=True)),
                ('cut_shear', models.CharField(blank=True, db_column='CUT_SHEAR', max_length=8, null=True)),
                ('rm_qty', models.DecimalField(blank=True, db_column='RM_QTY', decimal_places=3, max_digits=8, null=True)),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=4, null=True)),
                ('lc_no', models.CharField(blank=True, db_column='LC_NO', max_length=4, null=True)),
                ('opn', models.CharField(blank=True, db_column='OPN', max_length=3, null=True)),
                ('opn_desc', models.CharField(blank=True, db_column='OPN_DESC', max_length=30, null=True)),
                ('pa', models.DecimalField(blank=True, db_column='PA', decimal_places=2, max_digits=5, null=True)),
                ('at', models.DecimalField(blank=True, db_column='AT', decimal_places=2, max_digits=6, null=True)),
                ('no_off', models.DecimalField(blank=True, db_column='NO_OFF', decimal_places=0, max_digits=2, null=True)),
                ('m5_cd', models.CharField(blank=True, db_column='M5_CD', max_length=1, null=True)),
                ('pr_shopsec', models.CharField(blank=True, db_column='PR_SHOPSEC', max_length=4, null=True)),
                ('n_shopsec', models.CharField(blank=True, db_column='N_SHOPSEC', max_length=4, null=True)),
                ('qty_ord', models.DecimalField(blank=True, db_column='QTY_ORD', decimal_places=3, max_digits=8, null=True)),
                ('tot_rm_qty', models.DecimalField(blank=True, db_column='TOT_RM_QTY', decimal_places=3, max_digits=8, null=True)),
                ('l_fr', models.CharField(blank=True, db_column='L_FR', max_length=4, null=True)),
                ('l_to', models.CharField(blank=True, db_column='L_TO', max_length=4, null=True)),
                ('m5glsn', models.DecimalField(blank=True, db_column='M5GLSN', decimal_places=0, max_digits=6, null=True)),
                ('m5prtdt', models.DateField(blank=True, db_column='M5PRTDT', null=True)),
                ('seq', models.DecimalField(blank=True, db_column='SEQ', decimal_places=0, max_digits=3, null=True)),
                ('brn_no', models.DecimalField(blank=True, db_column='BRN_NO', decimal_places=0, max_digits=5, null=True)),
                ('mark', models.CharField(blank=True, db_column='MARK', max_length=1, null=True)),
                ('del_fl', models.CharField(blank=True, db_column='DEL_FL', max_length=1, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('qty_insp', models.IntegerField(blank=True, db_column='QTY_INSP', default=0, null=True)),
                ('inspector', models.IntegerField(blank=True, db_column='INSPECTOR', default=0, null=True)),
                ('date', models.CharField(blank='True', db_column='DATE', max_length=10, null='True')),
                ('remarks', models.CharField(blank='True', db_column='REMARKS', max_length=50, null='True')),
                ('worker', models.CharField(blank=True, db_column='WORKER', max_length=15, null=True)),
            ],
            options={
                'db_table': 'M5DOCnew',
            },
        ),
        migrations.CreateModel(
            name='M5SHEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(blank=True, db_column='YYMM', max_length=4, null=True)),
                ('shopsec', models.CharField(blank=True, db_column='SHOPSEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=5, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
                ('desgn', models.CharField(blank=True, db_column='DESGN', max_length=10, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('emp_type', models.CharField(blank=True, db_column='EMP_TYPE', max_length=3, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=1000, null=True)),
                ('updt_by', models.CharField(blank=True, db_column='UPDT_BY', max_length=6, null=True)),
                ('updt_date', models.DateField(blank=True, db_column='UPDT_DATE', null=True)),
                ('rec_ind', models.CharField(blank=True, db_column='REC_IND', max_length=1, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN1', max_length=10, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT', max_length=10, null=True)),
                ('ticket_no', models.IntegerField(blank=True, db_column='TICKET_NO', default=0, null=True)),
                ('month_hrs', models.IntegerField(blank=True, db_column='MONTH_HRS', default=0, null=True)),
                ('total_time_taken', models.IntegerField(blank=True, db_column='TOTAL_TIME_TAKEN', default=0, null=True)),
            ],
            options={
                'db_table': 'M5SHEMP',
            },
        ),
        migrations.AlterModelOptions(
            name='m14m4',
            options={'managed': False},
        ),
    ]
