# Generated by Django 2.0.7 on 2019-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_logbook_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='M5SHEMP1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopsec', models.CharField(blank=True, db_column='SHOPSEC', max_length=10, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('ticket_no', models.CharField(blank=True, db_column='TICKET_NO', default=0, max_length=20, null=True)),
                ('month_hrs', models.CharField(blank=True, db_column='MONTH_HRS', default=0, max_length=10, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN1', max_length=10, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT', max_length=10, null=True)),
                ('total_time_taken', models.CharField(blank=True, db_column='TOTAL_TIME_TAKEN', default=0, max_length=20, null=True)),
                ('in_date', models.CharField(blank=True, db_column='IN_DATE', max_length=10, null=True)),
                ('out_date', models.CharField(blank=True, db_column='OUT_DATE', max_length=10, null=True)),
                ('shift_typename', models.CharField(blank=True, db_column='SHIFT_TYPENAME', max_length=20, null=True)),
                ('flag', models.CharField(blank=True, db_column='FLAG', default='A', max_length=1, null=True)),
            ],
            options={
                'db_table': 'M5SHEMP1',
            },
        ),
        migrations.AlterField(
            model_name='m5docnew',
            name='batch_no',
            field=models.CharField(blank=True, db_column='BATCH_NO', max_length=8, null=True),
        ),
    ]
