# Generated by Django 2.0.7 on 2020-01-09 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_sanctionsse'),
    ]

    operations = [
        migrations.CreateModel(
            name='table1_id',
            fields=[
                ('bookno', models.CharField(db_column='BOOK_NO', max_length=10)),
                ('medical', models.CharField(db_column='MEDICAL_CNO', max_length=20, primary_key=True, serialize=False)),
                ('empno', models.CharField(db_column='EMP_NO', max_length=12)),
                ('demp_no', models.CharField(db_column='DEMP_NO', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='table2_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accdient', models.DateField(db_column='ACC_DATE')),
                ('part', models.CharField(db_column='PART_INJURED', max_length=100)),
                ('nature', models.CharField(db_column='NATURE_INJURY', max_length=200)),
                ('disability', models.IntegerField(db_column='DISABILITY_DAYS')),
                ('medicalcno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlw.table1_id')),
            ],
        ),
    ]
