# Generated by Django 2.0.7 on 2019-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20191206_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG5',
            fields=[
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=8, null=True)),
                ('name', models.CharField(blank=True, db_column='EMPLOYEE_NAME', max_length=8, null=True)),
                ('date', models.CharField(db_column=' DATE', max_length=50)),
                ('super_in', models.CharField(blank=True, db_column='SHOP_SUPERINTENDENT', max_length=25, null=True)),
                ('optr', models.CharField(db_column='OPERATOR', max_length=25)),
                ('chkr', models.CharField(db_column='TOOL_CHECKER', max_length=15)),
                ('id_no', models.CharField(db_column='IDENTITY CARD NO', max_length=10)),
                ('t_no', models.CharField(blank=True, db_column='TICKET_NO', max_length=35)),
                ('t_id', models.CharField(blank=True, db_column='TOOL_ID', max_length=35)),
                ('last_modified', models.CharField(db_column='LAST_MODIFIED', max_length=15)),
                ('to_no', models.AutoField(db_column='TOOL_ORDER_NO', max_length=5, primary_key=True, serialize=False)),
                ('t_desc', models.CharField(blank=True, db_column='TOOL_DESCRIPTION', max_length=50, null=True)),
            ],
            options={
                'db_table': 'MG5',
            },
        ),
    ]
