# Generated by Django 2.0.7 on 2020-02-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20200218_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2_transaction11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=10)),
                ('shop_sec', models.CharField(max_length=10)),
                ('part_no', models.CharField(max_length=10)),
                ('opn_no', models.CharField(max_length=10)),
                ('qty_prod', models.CharField(max_length=10)),
                ('qty_accep', models.CharField(max_length=10)),
                ('work_rej', models.CharField(max_length=10)),
                ('mat_rej', models.CharField(max_length=10)),
                ('inspect_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='acc_qty',
            field=models.IntegerField(blank=True, db_column='ACC_QTY', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='rej_mat',
            field=models.IntegerField(blank=True, db_column='REJ_MAT', default=0, null=True),
        ),
    ]
