# Generated by Django 2.0.7 on 2019-10-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20191010_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m14m4',
            options={},
        ),
    ]
