# Generated by Django 2.0.7 on 2019-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20191206_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='M18DOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopsec', models.CharField(blank=True, db_column='SHOPSEC', max_length=10, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=12, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('ticket_no', models.CharField(blank=True, db_column='TICKET_NO', default=0, max_length=20, null=True)),
                ('month', models.CharField(blank=True, db_column='MONTH', default=0, max_length=10, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN1', max_length=10, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT', max_length=10, null=True)),
                ('total_time_taken', models.CharField(blank=True, db_column='TOTAL_TIME_TAKEN', default=0, max_length=20, null=True)),
                ('in_date', models.CharField(blank=True, db_column='IN_DATE', max_length=10, null=True)),
                ('out_date', models.CharField(blank=True, db_column='OUT_DATE', max_length=10, null=True)),
                ('shift_typename', models.CharField(blank=True, db_column='SHIFT_TYPENAME', max_length=20, null=True)),
                ('req_no', models.CharField(blank=True, db_column='REQ_NO', max_length=10, null=True)),
            ],
            options={
                'db_table': 'M18DOC',
            },
        ),
        migrations.CreateModel(
            name='M24',
            fields=[
                ('sno', models.AutoField(db_column='SL.No', primary_key=True, serialize=False)),
                ('fr_date', models.CharField(db_column='FR_DATE', max_length=20, null=True)),
                ('to_date', models.CharField(db_column='TO_DATE', max_length=20, null=True)),
                ('shop_sec', models.CharField(db_column='SHOPSEC', max_length=20, null=True)),
                ('ssfo', models.CharField(db_column='SSFO', max_length=20, null=True)),
                ('timekeep', models.CharField(db_column='TIMEKEEPER', max_length=30, null=True)),
                ('workshop', models.CharField(db_column='WORKSHOPS', max_length=30, null=True)),
                ('staff_no', models.CharField(db_column='STAFF_NO', max_length=20, null=True)),
                ('desgn', models.CharField(db_column='DESIGNATION', max_length=20, null=True)),
                ('payrate', models.CharField(db_column='RATE_PAY', max_length=20, null=True)),
                ('hrs_wrked', models.CharField(db_column='HOURS_WRKD', max_length=20, null=True)),
                ('rsn_ovrtym', models.CharField(db_column='OVERTIME_REASON', max_length=20, null=True)),
                ('supervise_chrgmn', models.CharField(db_column='SUPERVISOR', max_length=50, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LAST_MODIFIED', null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
            ],
        ),
    ]
