# Generated by Django 2.0.7 on 2019-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20191107_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='axlewheelmachining',
            name='axleinspection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='wheelinspection_status',
            field=models.BooleanField(default=False),
        ),
    ]
