# Generated by Django 2.0.7 on 2020-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_table1_id_table2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1_id',
            name='bookno',
            field=models.CharField(db_column='BOOK_NO', max_length=20),
        ),
    ]
