# Generated by Django 2.0.7 on 2019-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_mg5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mg5',
            name='staff_no',
            field=models.CharField(blank=True, db_column='STAFF_NO', max_length=12, null=True),
        ),
    ]
