# Generated by Django 2.0.7 on 2019-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_auto_20191010_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m14m4',
            name='laser_pst',
            field=models.CharField(blank=True, db_column='LASER_PST', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='posted1_date',
            field=models.CharField(blank=True, db_column='POSTED1_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='posted_date',
            field=models.CharField(blank=True, db_column='POSTED_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='received_mat',
            field=models.CharField(blank=True, db_column='RECEIVED_MAT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='received_qty',
            field=models.CharField(blank=True, db_column='RECEIVED_QTY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='shopsup_date',
            field=models.CharField(blank=True, db_column='SHOPSUP_DATE', default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='m14m4',
            name='wardkp_date',
            field=models.CharField(blank=True, db_column='WARDKP_DATE', default=0, max_length=50),
        ),
    ]
