# Generated by Django 2.0.7 on 2020-02-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_auto_20200218_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
    ]
