# Generated by Django 2.0.7 on 2019-12-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_m2hw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2HW',
        ),
    ]
