# Generated by Django 2.0.7 on 2019-10-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20191010_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m14m4',
            options={'managed': False},
        ),
    ]
