# Generated by Django 2.0.7 on 2020-02-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20200218_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'managed': False},
        ),
    ]
