# Generated by Django 2.0.7 on 2019-12-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20191213_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mg5',
            name='name',
            field=models.CharField(blank=True, db_column='EMPLOYEE_NAME', max_length=30, null=True),
        ),
    ]
