# Generated by Django 2.0.7 on 2019-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20191108_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='roleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navmenu', models.CharField(blank=True, max_length=30, null=True)),
                ('navitem', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
