# Generated by Django 2.0.7 on 2020-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20200109_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2_id',
            name='accdient',
            field=models.CharField(db_column='ACC_DATE', max_length=12),
        ),
    ]
