# Generated by Django 2.0.7 on 2019-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_auto_20191010_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m5shemp',
            name='shopsec',
            field=models.CharField(blank=True, db_column='SHOPSEC', max_length=10, null=True),
        ),
    ]
