# Generated by Django 2.0.7 on 2020-02-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_auto_20200218_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='m5docnew',
            name='acc_qty',
            field=models.IntegerField(blank=True, db_column='ACC_QTY', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew',
            name='rej_mat',
            field=models.IntegerField(blank=True, db_column='REJ_MAT', default=0, null=True),
        ),
    ]
