# Generated by Django 2.0.7 on 2019-10-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_auto_20191010_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m14m4',
            options={},
        ),
    ]
