# Generated by Django 2.0.7 on 2019-11-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_rolemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewUrlPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitem', models.CharField(blank=True, max_length=50, null=True)),
                ('urlname', models.CharField(blank=True, max_length=50, null=True)),
                ('rolespermission', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
