# Generated by Django 2.0.7 on 2019-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_auto_20191213_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mg5',
            name='shop_sec',
            field=models.CharField(blank=True, db_column='SHOP_SEC', max_length=10, null=True),
        ),
    ]
