# Generated by Django 2.0.7 on 2020-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_auto_20200219_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='axlemachining',
            name='collaraxlende',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='axlemachining',
            name='journalaxlende',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='axlemachining',
            name='throweraxlende',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='axlemachining',
            name='wheelseataxlende',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
