# Generated by Django 2.0.7 on 2019-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_auto_20191010_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m5shemp',
            name='cat',
            field=models.CharField(blank=True, db_column='CAT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='m5shemp',
            name='emp_type',
            field=models.CharField(blank=True, db_column='EMP_TYPE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m5shemp',
            name='rec_ind',
            field=models.CharField(blank=True, db_column='REC_IND', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m5shemp',
            name='status',
            field=models.CharField(blank=True, db_column='STATUS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m5shemp',
            name='updt_by',
            field=models.CharField(blank=True, db_column='UPDT_BY', max_length=20, null=True),
        ),
    ]
