# Generated by Django 2.0.7 on 2019-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_m2hw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2hw',
            name='prtDate',
            field=models.DateField(db_column='PRINTDATE', max_length=20),
        ),
    ]
