# Generated by Django 2.0.7 on 2020-01-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_fitcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG21TAB',
            fields=[
                ('shop_sec', models.CharField(blank=True, db_column='shop_sec', default=0, max_length=30, null=True)),
                ('staffNo', models.CharField(db_column='staffNo', max_length=20, primary_key=True, serialize=False)),
                ('staffName', models.CharField(db_column='staffName', max_length=50, null=True)),
                ('staffDesg', models.CharField(db_column='staffDesg', max_length=50, null=True)),
                ('reportdate', models.CharField(db_column='reportdate', max_length=20, null=True)),
                ('resumedate', models.CharField(blank=True, db_column='resumedate', max_length=20, null=True)),
                ('sse', models.CharField(blank=True, db_column='sse', default=0, max_length=50, null=True)),
                ('reportno', models.CharField(db_column='reportno', max_length=20, null=True)),
                ('login_id', models.CharField(blank=True, db_column='login_id', max_length=20, null=True)),
                ('current_date', models.CharField(blank=True, db_column='current_date', max_length=20, null=True)),
            ],
            options={
                'db_table': 'MG21TAB',
            },
        ),
    ]
