# Generated by Django 2.0.7 on 2019-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_viewurlpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='M30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=8, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=10, null=True)),
                ('req', models.CharField(blank=True, db_column='REQUEST', max_length=25, null=True)),
                ('date', models.CharField(blank=True, db_column='date', default='0', max_length=10, null=True)),
                ('waiver_date', models.CharField(blank=True, db_column='WAIVER_DATE', default='0', max_length=10, null=True)),
                ('qty', models.CharField(blank=True, db_column='QUANTITY', max_length=8, null=True)),
                ('dimension', models.CharField(blank=True, db_column='DIMENSION', max_length=15, null=True)),
                ('spe_val', models.CharField(blank=True, db_column='SPECIFIED VALUE', max_length=10, null=True)),
                ('obt_val', models.CharField(blank=True, db_column='OBTAINED VALUE', max_length=10, null=True)),
                ('interc', models.CharField(blank=True, db_column='INTERCHANGEABLITY', max_length=50, null=True)),
                ('waiver_no', models.CharField(blank=True, db_column='WAIVER_NO', max_length=12, null=True)),
                ('non_conf_des', models.CharField(blank=True, db_column='NON_CONFORMANCE_DES', max_length=50, null=True)),
                ('reason_for_non_conf', models.CharField(blank=True, db_column='REASON_CONFORMANCE', max_length=50, null=True)),
                ('corr_action_plan', models.CharField(blank=True, db_column='CORRECTIVE_ACTION_PLAN', max_length=50, null=True)),
                ('remarks_hod', models.CharField(blank=True, db_column='REMARKS_HOD', max_length=50, null=True)),
                ('remarks_cqam', models.CharField(blank=True, db_column='REMARKS_CQAM', max_length=50, null=True)),
                ('remarks_cde', models.CharField(blank=True, db_column='REMARKS_CDE', max_length=50, null=True)),
                ('loco_fr', models.CharField(blank=True, db_column='LOCO_FROM', max_length=10, null=True)),
                ('loco_to', models.CharField(blank=True, db_column='LOCO_TO', max_length=10, null=True)),
                ('request_no', models.CharField(blank=True, db_column='REQUEST_NO', max_length=15, null=True)),
                ('specification_no', models.CharField(blank=True, db_column='SPECIFICATION_NUMBER', max_length=15, null=True)),
            ],
            options={
                'db_table': 'M30',
            },
        ),
    ]
