# Generated by Django 2.0.7 on 2019-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_m30'),
    ]

    operations = [
        migrations.AddField(
            model_name='axlewheelmachining',
            name='ustaxle_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='ustaxle_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='ustwhl_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='axlewheelmachining',
            name='ustwhl_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
