# Generated by Django 2.0.7 on 2019-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20191214_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2hw',
            name='shopSecTemp',
            field=models.CharField(blank=True, db_column='SHOPSECTEMP', max_length=15, null=True),
        ),
    ]
