# Generated by Django 2.0.7 on 2020-02-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20200219_1541'),
    ]

    operations = [
    ]
