# Generated by Django 2.0.7 on 2020-01-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_mg21tab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intershop',
        ),
    ]
