# Generated by Django 2.0.7 on 2019-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20191010_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m5shemp',
            name='cat',
            field=models.CharField(blank=True, db_column='CAT', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='m5shemp',
            name='month_hrs',
            field=models.CharField(blank=True, db_column='MONTH_HRS', default=0, max_length=10, null=True),
        ),
    ]
