# Generated by Django 2.0.7 on 2020-02-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0026_auto_20200220_1310'),
    ]

    operations = [
    ]
