# Generated by Django 2.0.7 on 2019-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0026_auto_20191113_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machiningairbox',
            name='in_qty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='machiningairbox',
            name='out_qty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
