# Generated by Django 2.0.7 on 2019-10-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0026_auto_20191010_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M5SHEMP',
        ),
    ]
