# Generated by Django 2.0.7 on 2020-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0027_auto_20200220_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='m5docnew1',
            name='date',
            field=models.CharField(blank='True', db_column='DATE', max_length=10, null='True'),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='inspector',
            field=models.IntegerField(blank=True, db_column='INSPECTOR', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='qty_insp',
            field=models.IntegerField(blank=True, db_column='QTY_INSP', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='rej_qty',
            field=models.IntegerField(blank=True, db_column='REJ_QTY', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='remarks',
            field=models.CharField(blank='True', db_column='REMARKS', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='rev_qty',
            field=models.IntegerField(blank=True, db_column='REV_QTY', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew1',
            name='worker',
            field=models.CharField(blank=True, db_column='WORKER', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='m14m4new1',
            name='bo_no',
            field=models.CharField(blank=True, db_column='BO_NO', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='m2docnew1',
            name='batch_no',
            field=models.CharField(blank=True, db_column='BATCH_NO', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='m5docnew1',
            name='batch_no',
            field=models.CharField(blank=True, db_column='BATCH_NO', max_length=8, null=True),
        ),
    ]
