# Generated by Django 2.0.7 on 2019-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0027_remove_m2hw_prtdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2hw',
            name='asmlyDesc',
            field=models.CharField(db_column='ASMLYDESC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='asmlyPartNo',
            field=models.CharField(db_column='ASMLYPARTNO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='brnNo',
            field=models.CharField(db_column='BRNNO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='documentNum',
            field=models.CharField(db_column='DOCUMENTNUMBER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='drawingNum',
            field=models.CharField(db_column='DRAWINGNUMBER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='loadCenter',
            field=models.CharField(blank=True, db_column='LOADCENTER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='matrej',
            field=models.CharField(db_column='MATREJ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='noTemp',
            field=models.CharField(db_column='NOTEMP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='number',
            field=models.CharField(db_column='UNIQUENUM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='operationDescription',
            field=models.CharField(db_column='OPERATIONDESCRIPTION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='orderQuantity',
            field=models.CharField(db_column='ORDERQUANTITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='orderType',
            field=models.CharField(db_column='ORDERTYPE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='paTemp',
            field=models.CharField(db_column='PATEMP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='partDescription',
            field=models.CharField(db_column='PARTDESCRIPTION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='partNum',
            field=models.CharField(db_column='PARTNUM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='qtyac',
            field=models.CharField(db_column='QTYAC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='qtypr',
            field=models.CharField(db_column='QTYPR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='shopSecTemp',
            field=models.CharField(blank=True, db_column='SHOPSECTEMP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='shopSection',
            field=models.CharField(db_column='SHOPSECTION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='taTemp',
            field=models.CharField(db_column='TATEMP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='workOrdNo',
            field=models.CharField(db_column='WONO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='wrrej',
            field=models.CharField(db_column='WRREJ', max_length=50, null=True),
        ),
    ]
