# Generated by Django 2.0.7 on 2019-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0027_auto_20191113_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='M15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('shop', models.CharField(blank=True, max_length=4, null=True)),
                ('wo', models.CharField(blank=True, max_length=7, null=True)),
                ('part_no', models.CharField(blank=True, max_length=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=8, null=True)),
                ('allocation', models.CharField(blank=True, max_length=8, null=True)),
                ('rate', models.CharField(blank=True, max_length=8, null=True)),
                ('rupees', models.CharField(blank=True, max_length=10, null=True)),
                ('paise', models.CharField(blank=True, max_length=10, null=True)),
                ('mat_ret_date', models.CharField(blank=True, max_length=10, null=True)),
                ('mat_rec_date', models.CharField(blank=True, max_length=10, null=True)),
                ('m13_no', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('c_d_no', models.CharField(blank=True, max_length=10, null=True)),
                ('qty_ret', models.CharField(blank=True, max_length=10, null=True)),
                ('qty_rec_inward', models.CharField(blank=True, max_length=10, null=True)),
                ('metric_ton_returned', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_ton_received', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
