# Generated by Django 2.0.7 on 2019-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0027_delete_m5shemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='M5SHEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(blank=True, db_column='YYMM', max_length=4, null=True)),
                ('shopsec', models.CharField(blank=True, db_column='SHOPSEC', max_length=10, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
                ('desgn', models.CharField(blank=True, db_column='DESGN', max_length=10, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('emp_type', models.CharField(blank=True, db_column='EMP_TYPE', max_length=10, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=10, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=1000, null=True)),
                ('updt_by', models.CharField(blank=True, db_column='UPDT_BY', max_length=20, null=True)),
                ('updt_date', models.DateField(blank=True, db_column='UPDT_DATE', null=True)),
                ('ticket_no', models.IntegerField(blank=True, db_column='TICKET_NO', default=0, null=True)),
                ('rec_ind', models.CharField(blank=True, db_column='REC_IND', max_length=10, null=True)),
                ('month_hrs', models.CharField(blank=True, db_column='MONTH_HRS', default=0, max_length=10, null=True)),
                ('total_time_taken', models.IntegerField(blank=True, db_column='TOTAL_TIME_TAKEN', default=0, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN1', max_length=10, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT', max_length=10, null=True)),
            ],
            options={
                'db_table': 'M5SHEMP',
            },
        ),
    ]
