# Generated by Django 2.0.7 on 2020-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0028_auto_20200220_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwm5inbox',
            name='cardstatus',
            field=models.CharField(blank=True, db_column='CARD_STATUS', max_length=2, null=True),
        ),
    ]
