# Generated by Django 2.0.7 on 2019-11-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0028_m15'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shemp',
            options={},
        ),
    ]
