# Generated by Django 2.0.7 on 2019-10-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0028_m5shemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M5SHEMP',
        ),
    ]
