# Generated by Django 2.0.7 on 2019-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0028_auto_20191214_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2hw',
            name='asmlyDesc',
            field=models.CharField(db_column='ASMLYDESC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='operationDescription',
            field=models.CharField(db_column='OPERATIONDESCRIPTION', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m2hw',
            name='partDescription',
            field=models.CharField(db_column='PARTDESCRIPTION', max_length=100, null=True),
        ),
    ]
