# Generated by Django 2.0.7 on 2019-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0029_auto_20191114_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='shemp',
            name='ticket_no',
            field=models.CharField(blank=True, db_column='TICKET_NO', max_length=20, null=True),
        ),
    ]
