# Generated by Django 2.0.7 on 2020-02-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0029_hwm5inbox_cardstatus'),
    ]

    operations = [
    ]
