# Generated by Django 2.0.7 on 2020-02-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0030_auto_20200224_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=15, null=True)),
                ('login_id', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('pl_no', models.CharField(max_length=10, null=True)),
                ('engine_loco_type', models.CharField(max_length=100, null=True)),
                ('supplier_name', models.CharField(max_length=50, null=True)),
                ('rejection_percentage', models.CharField(max_length=8, null=True)),
                ('past_failure_details', models.CharField(max_length=200, null=True)),
                ('reporting_agency_name', models.CharField(max_length=150, null=True)),
                ('failure_since_last_six_months', models.CharField(max_length=200, null=True)),
                ('probable_cause_redemy', models.CharField(max_length=200, null=True)),
                ('employee_id', models.CharField(max_length=20, null=True)),
                ('ca_regis_no', models.CharField(max_length=15, null=True)),
                ('date_by_mroffice', models.CharField(max_length=20, null=True)),
                ('follow_up', models.CharField(max_length=200, null=True)),
                ('mr_office_decision', models.CharField(max_length=200, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
