# Generated by Django 2.0.7 on 2019-10-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20191010_1653'),
        ('dlw', '0030_m5shemp'),
    ]

    operations = [
    ]
