# Generated by Django 2.0.7 on 2019-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0031_merge_20191010_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinionPressing',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bo_no', models.CharField(max_length=20, null=True)),
                ('bo_date', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('tm_no', models.CharField(max_length=20, null=True)),
                ('tm_make', models.CharField(max_length=20, null=True)),
                ('pinion_no', models.CharField(max_length=20, null=True)),
                ('pinion_make', models.CharField(max_length=20, null=True)),
                ('pinion_travel', models.CharField(max_length=20, null=True)),
                ('pinion_pressure', models.CharField(max_length=20, null=True)),
                ('blue_match', models.CharField(max_length=20, null=True)),
                ('loco_type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
