# Generated by Django 2.0.7 on 2020-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0032_auto_20200228_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='toolmdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOOL_NUM', models.CharField(blank=True, db_column='TOOL_NUM', default=0, max_length=15, null=True)),
                ('dg_num', models.CharField(db_column='DG_NUM', max_length=35, null=True)),
                ('tl_desc', models.CharField(blank=True, db_column='TOOL_DESCRIPTION', max_length=35, null=True)),
                ('pl_num', models.CharField(db_column='PL_NUMP', max_length=20, null=True)),
                ('sh_locn', models.CharField(db_column='SHOP_LOCATION', max_length=15, null=True)),
                ('tr_shopdesc', models.CharField(db_column='SHOP_DESCRIPTION', max_length=15, null=True)),
                ('po_no', models.CharField(db_column='po_no', max_length=15, null=True)),
                ('doe', models.CharField(db_column='DATE_OF_ENTRY', max_length=15, null=True)),
                ('make', models.CharField(db_column='MAKE', max_length=15, null=True)),
                ('model', models.CharField(db_column='MODEL', max_length=15, null=True)),
                ('cost', models.CharField(db_column='COST', max_length=15, null=True)),
                ('rangee', models.CharField(db_column='Rangee', max_length=15, null=True)),
                ('uom', models.CharField(db_column='UNIT_OF_MEASUREMENT', max_length=15, null=True)),
                ('cal_freq', models.CharField(db_column='CALIBRATION_FREQUENCY', max_length=15, null=True)),
                ('acc_cri', models.CharField(db_column='ACCURACY_CRITERIA', max_length=15, null=True)),
                ('cal_link', models.CharField(db_column='CALIBRATION_LINK', max_length=15, null=True)),
                ('pro_tol', models.CharField(db_column='PROCESS_TOLERANCE', max_length=15, null=True)),
                ('perror', models.CharField(db_column='PLUS_ERROR', max_length=15, null=True)),
                ('merror', models.CharField(db_column='MINUS_ERROR', max_length=15, null=True)),
                ('rsn', models.CharField(db_column='REFRENCE_STANDARD_NUMBER', max_length=15, null=True)),
                ('win', models.CharField(db_column='WORK_INSTRUCTION_NUMBER', max_length=15, null=True)),
                ('flag', models.CharField(db_column='flag', max_length=2, null=True)),
                ('lastupddate', models.CharField(db_column='LastUpdateDate', max_length=15, null=True)),
                ('user', models.CharField(db_column='User', max_length=15, null=True)),
            ],
        ),
    ]
