# Generated by Django 2.0.7 on 2019-11-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0032_mg15'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG49',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopsec', models.CharField(blank=True, max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('part_no', models.CharField(blank=True, max_length=8, null=True)),
                ('desc', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('quan', models.FloatField(blank=True, default=0, max_length=25, null=True)),
                ('weight', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('login_id', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('last_modified', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default=0, max_length=25, null=True)),
            ],
        ),
    ]
