# Generated by Django 2.0.7 on 2019-11-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0033_mg49'),
    ]

    operations = [
        migrations.AddField(
            model_name='m5docnew',
            name='rej_qty',
            field=models.IntegerField(blank=True, db_column='REJ_QTY', default=0, null=True),
        ),
        migrations.AddField(
            model_name='m5docnew',
            name='rev_qty',
            field=models.IntegerField(blank=True, db_column='REV_QTY', default=0, null=True),
        ),
    ]
