# Generated by Django 2.0.7 on 2019-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0033_dpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='subnavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentmenu', models.CharField(max_length=50, null=True)),
                ('childmenu', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
