# Generated by Django 2.0.7 on 2019-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0034_auto_20191115_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, db_column='TO', max_length=30, null=True)),
                ('date', models.CharField(blank=True, db_column='DATE', max_length=30, null=True)),
                ('namaddr', models.CharField(blank=True, db_column='NAME_FACT', max_length=30, null=True)),
                ('empcode', models.CharField(blank=True, db_column='EMP_CODE', max_length=30, null=True)),
                ('natindus', models.CharField(blank=True, db_column='NATUREINDUS', max_length=30, null=True)),
                ('addr_accdnt', models.CharField(blank=True, db_column='ADDR_ACCDNT', max_length=30, null=True)),
                ('brnchdept', models.CharField(blank=True, db_column='BRANCH', max_length=30, null=True)),
                ('namadrr_inj', models.CharField(blank=True, db_column='INJ_ADDR', max_length=30, null=True)),
                ('insur_no', models.CharField(blank=True, db_column='INSURANCE', max_length=30, null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=10, null=True)),
                ('age_lstbrth', models.CharField(blank=True, db_column='AGE', max_length=30, null=True)),
                ('occup_inj', models.CharField(blank=True, db_column='OCCUPATION', max_length=30, null=True)),
                ('dthrs_accdnt', models.CharField(blank=True, db_column='DTHRS_ACCD', max_length=30, null=True)),
                ('hr_strtwrk', models.CharField(blank=True, db_column='STRTWORK', max_length=30, null=True)),
                ('cause_accndt', models.CharField(blank=True, db_column='CAUSE_ACCDNT', max_length=30, null=True)),
                ('mach_accdnt', models.CharField(blank=True, db_column='MACHINE_PART', max_length=30, null=True)),
                ('mach_mov', models.CharField(blank=True, db_column='MACHINE_MOV', max_length=30, null=True)),
                ('inj_doing', models.CharField(blank=True, db_column='INJR_DOING', max_length=30, null=True)),
                ('inj_extent', models.CharField(blank=True, db_column='EXTENT', max_length=30, null=True)),
                ('inj_off', models.CharField(blank=True, db_column='DAYSOFF', max_length=30, null=True)),
                ('name_doct', models.CharField(blank=True, db_column='DOCTORNAME', max_length=30, null=True)),
                ('inj_evid', models.CharField(blank=True, db_column='EVIDENCE', max_length=30, null=True)),
                ('how_accdnt', models.CharField(blank=True, db_column='HOW', max_length=30, null=True)),
                ('inj_loc', models.CharField(blank=True, db_column='LOCATION', max_length=30, null=True)),
                ('inj_retrn', models.CharField(blank=True, db_column='RETURN_NOT', max_length=25, null=True)),
                ('dthr_retrn', models.CharField(blank=True, db_column='RETURN_DTHRS', max_length=20, null=True)),
                ('inj_died', models.CharField(blank=True, db_column='DIED_INJ', max_length=20, null=True)),
                ('dt_death', models.CharField(blank=True, db_column='DEATH_DT', max_length=20, null=True)),
                ('stloc_insur', models.CharField(blank=True, db_column='LOCAL_INSUR', max_length=25, null=True)),
                ('stinsur_dispns', models.CharField(blank=True, db_column='LOCAL_DISPENS', max_length=20, null=True)),
                ('distrct', models.CharField(blank=True, db_column='DISTRICT', max_length=30, null=True)),
                ('dt_receipt', models.CharField(blank=True, db_column='RECIEPT_DT', max_length=30, null=True)),
                ('accdnt_no', models.CharField(blank=True, db_column='ACCNDT_NO', max_length=30, null=True)),
                ('indus_no', models.CharField(blank=True, db_column='INDUSTRY_NO', max_length=30, null=True)),
                ('cause_no', models.CharField(blank=True, db_column='CAUSATION', max_length=30, null=True)),
                ('sex_1', models.CharField(blank=True, db_column='SEX_11', max_length=30, null=True)),
                ('particulars', models.CharField(blank=True, db_column='PARTICUL', max_length=30, null=True)),
                ('dt_invstgtn', models.CharField(blank=True, db_column='INVESTIGATION_DT', max_length=30, null=True)),
                ('rslt_invstgtn', models.CharField(blank=True, db_column='RESLT_INVST', max_length=30, null=True)),
                ('effct_frm', models.CharField(blank=True, db_column='EFFECT', max_length=30, null=True)),
            ],
            options={
                'db_table': 'MG18',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rate', models.DecimalField(blank=True, db_column='AVG_RATE', decimal_places=2, max_digits=6, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LAST_MODIFIED', null=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', max_length=15, null=True)),
            ],
            options={
                'db_table': 'RATES',
            },
        ),
    ]
