# Generated by Django 2.0.7 on 2019-10-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0034_subnavbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpo',
            name='copyto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dpo',
            name='reference',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dpo',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dpo',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
