# Generated by Django 2.0.7 on 2019-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0035_mg18_rates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M11',
        ),
        migrations.AddField(
            model_name='m12doc',
            name='amt',
            field=models.DecimalField(blank=True, db_column='AMT', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='m12doc',
            name='time_hrs',
            field=models.CharField(blank=True, db_column='TIME_HRS', max_length=10, null=True),
        ),
    ]
