# Generated by Django 2.0.7 on 2019-10-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0035_auto_20191015_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpoinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureno', models.CharField(max_length=50, null=True)),
                ('loconame', models.CharField(max_length=50, null=True)),
                ('locotype', models.CharField(max_length=50, null=True)),
                ('endcumno', models.CharField(max_length=10, null=True)),
                ('orderno', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dpo',
            old_name='loconame',
            new_name='procedureno',
        ),
        migrations.RemoveField(
            model_name='dpo',
            name='endcumno',
        ),
        migrations.AddField(
            model_name='miscellsection',
            name='dispatch_status',
            field=models.BooleanField(default=False),
        ),
    ]
