# Generated by Django 2.0.7 on 2019-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0035_auto_20191015_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpoinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureno', models.CharField(max_length=50, null=True)),
                ('loconame', models.CharField(max_length=50, null=True)),
                ('locotype', models.CharField(max_length=50, null=True)),
                ('endcumno', models.CharField(max_length=10, null=True)),
                ('orderno', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dpor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureno', models.CharField(max_length=50, null=True)),
                ('locotype', models.CharField(max_length=50, null=True)),
                ('orderno', models.CharField(max_length=10, null=True)),
                ('subject', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('copyto', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='M7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=5, null=True)),
                ('wo_no', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('part_no', models.CharField(blank=True, max_length=8, null=True)),
                ('cat', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('in1', models.CharField(blank=True, max_length=10, null=True)),
                ('out', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'M7',
            },
        ),
        migrations.DeleteModel(
            name='dpo',
        ),
    ]
