# Generated by Django 2.0.7 on 2019-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0036_auto_20191118_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='M11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(blank=True, db_column='YYMM', max_length=4, null=True)),
                ('shopsec', models.CharField(blank=True, db_column='SHOPSEC', max_length=4, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='STAFF_NO', max_length=5, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
                ('desgn', models.CharField(blank=True, db_column='DESGN', max_length=10, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('emp_type', models.CharField(blank=True, db_column='EMP_TYPE', max_length=3, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=1000, null=True)),
                ('updt_by', models.CharField(blank=True, db_column='UPDT_BY', max_length=6, null=True)),
                ('updt_date', models.DateField(blank=True, db_column='UPDT_DATE', null=True)),
                ('rec_ind', models.CharField(blank=True, db_column='REC_IND', max_length=1, null=True)),
                ('in1', models.CharField(blank=True, db_column='IN1', max_length=10, null=True)),
                ('out', models.CharField(blank=True, db_column='OUT', max_length=10, null=True)),
                ('date', models.CharField(blank=True, db_column='DATE', max_length=10, null=True)),
                ('month', models.CharField(blank=True, db_column='MONTH', max_length=15, null=True)),
                ('total_time', models.CharField(blank=True, db_column='TOTAL_TIME', max_length=10, null=True)),
                ('idle_time', models.CharField(blank=True, db_column='IDLE_TIME', max_length=10, null=True)),
                ('amt', models.CharField(blank=True, db_column='AMOUNT', max_length=7, null=True)),
                ('detail_no', models.CharField(db_column='IT_reasons', max_length=70, null=True)),
            ],
            options={
                'db_table': 'M11',
            },
        ),
    ]
