# Generated by Django 2.0.7 on 2019-10-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0036_auto_20191015_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dpor',
            new_name='dpo',
        ),
    ]
