# Generated by Django 2.0.7 on 2019-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0037_auto_20191015_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinionpressing',
            name='dispatch_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pinionpressing',
            name='dispatch_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
