# Generated by Django 2.0.7 on 2019-11-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0037_m11'),
    ]

    operations = [
        migrations.CreateModel(
            name='MG33new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_sec', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ticketno', models.CharField(blank=True, max_length=10, null=True)),
                ('acc_date', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_exam', models.CharField(blank=True, max_length=50, null=True)),
                ('sec_sup', models.CharField(blank=True, max_length=50, null=True)),
                ('prac_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('oral_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('prac_score', models.CharField(blank=True, max_length=10, null=True)),
                ('oral_score', models.CharField(blank=True, max_length=10, null=True)),
                ('total_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_test_officer', models.CharField(blank=True, max_length=50, null=True)),
                ('foreman', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_test_admin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
