from .qtysum import *
from .workdemandbyshop import *
from .labourrateupdation import *
from .mnpmastermnt import *
from .screenforloadmasmnt import *
from .capacityplanning import *
from .mgrview import *
from .createcpm import *
from .jbsdoc import *
from .secjoblisting import *
from .spptalot import *
from .cnote import *
from .roster import *
from .sickcertificate import *
from .employeeregistration import *